import type { Dictionary } from './types'

export const en: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'Loading...',
    errorTitle: 'Something went wrong',
    errorGeneric: 'We could not complete the action. Please try again.',
    retry: 'Try again',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Saved',
    cancel: 'Cancel',
    back: 'Back',
    search: 'Search',
    all: 'All',
    none: 'None',
    today: 'Today',
    signOut: 'Sign out',
    language: 'Language',
    copy: 'Copy',
    copied: 'Copied',
    patient: 'Patient',
    phone: 'Mobile',
    email: 'Email',
    name: 'Name',
    reason: 'Reason',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    actions: 'Actions',
    summary: 'Summary',
    of: 'of',
    thisMonth: 'this month',
    optional: 'optional',
  },
  status: {
    appointment: {
      pendente: 'To confirm',
      confirmada: 'Confirmed',
      rejeitada: 'Rejected',
      copiada: 'Copied to system',
    },
    clinic: { ativa: 'Active', pausada: 'Paused', cancelada: 'Cancelled' },
    call: {
      marcacao: 'Booking',
      transferida: 'Transferred',
      informacao: 'Information',
      nao_resolvida: 'Unresolved',
    },
    origin: { telefone: 'Phone', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Essencial',
    clinica: 'Clínica',
    rede: 'Rede',
    personalizado: 'Personalizado',
  },
  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  auth: {
    title: 'Sign in',
    subtitle: 'Access your clinic dashboard.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalid: 'Wrong email or password.',
  },
  clinicNav: {
    hoje: 'Today',
    marcacoes: 'Bookings',
    horarios: 'Hours',
    chamadas: 'Calls',
    conta: 'My clinic',
  },
  internoNav: {
    clinicas: 'Clinics',
    consumo: 'Usage',
    atividade: 'Activity',
  },
  hoje: {
    title: 'Today',
    greeting: 'Your clinic day with Telma.',
    live: 'Updating in real time',
    pendingTitle: 'To confirm',
    pendingEmpty: 'No bookings to confirm.',
    callsTitle: 'Calls today',
    callsEmpty: 'Telma has not answered any calls today yet.',
    seeAll: 'See all calls',
  },
  marcacoes: {
    title: 'Bookings',
    help: 'Telma leaves bookings here. Confirm each one and copy it into your clinic software.',
    empty: 'No bookings right now.',
    confirm: 'Confirm',
    alter: 'Change',
    reject: 'Reject',
    copyData: 'Copy patient details',
    copiedToSystem: 'Copied to clinic system',
    copiedToSystemHint: 'You can now copy this booking into your software.',
    alterWarning: 'When you change the date or time, the patient must be told.',
    newDateTime: 'New date and time',
    rejectReason: 'Reason (optional)',
    rejectReasonHint: 'Kept for the record, the patient is not told automatically.',
    confirmConfirm: 'Mark as confirmed',
    filterAll: 'All',
    filterPending: 'To confirm',
  },
  horarios: {
    title: 'Hours',
    help: 'Telma only offers these hours. She will never book outside them.',
    gridHint: 'Tap the hours you want to offer on each day.',
    capacityNote: 'Each hour takes one booking. Talk to us to change this.',
    blockedTitle: 'Blocked days',
    blockedHelp: 'Public holidays and time off. Telma books nothing on these days.',
    addBlock: 'Block a day',
    blockDayLabel: 'Day to block',
    blockReason: 'Reason',
    noBlocked: 'No blocked days.',
    remove: 'Remove',
    saving: 'Saving...',
  },
  chamadas: {
    title: 'Calls',
    filterResult: 'Result',
    filterFrom: 'From',
    filterTo: 'To',
    empty: 'No calls for these filters.',
    detail: 'Call detail',
    noSummary: 'No summary.',
    audio: 'Recording',
    noAudio: 'No recording available.',
    duration: 'Duration',
  },
  conta: {
    title: 'My clinic',
    clinicData: 'Clinic details',
    plan: 'Plan',
    addon: 'Telma on WhatsApp',
    addonOn: 'Active',
    addonOff: 'Not active',
    usageTitle: 'Usage this month',
    callsUsed: 'Calls used',
    limit: 'Plan limit',
    contactSupport: 'To change your plan or details, talk to us.',
  },
  interno: {
    clinicsTitle: 'Clinics',
    clinicsSubtitle: 'Every clinic and its usage this month.',
    searchPlaceholder: 'Search by name...',
    colName: 'Clinic',
    colPlan: 'Plan',
    colStatus: 'Status',
    colUsage: 'Calls / limit',
    colActivity: 'Last activity',
    overLimit: 'Over limit',
    nearLimit: 'Near limit',
    newClinic: 'New clinic',
    never: 'No activity',
    fichaData: 'Details',
    fichaTechnical: 'Technical config',
    assignedPhone: 'Assigned number',
    agentId: 'Voice agent id',
    voiceName: 'Voice',
    fichaSlots: 'Configured hours',
    fichaCalls: 'Recent calls',
    fichaAppointments: 'Recent bookings',
    openFicha: 'Open clinic',
    newTitle: 'New clinic',
    newHelp: 'Creates the clinic, its first user and the default hours.',
    fieldClinicName: 'Clinic name',
    fieldAddress: 'Address',
    fieldPhone: 'Clinic phone',
    fieldContactEmail: 'Contact email',
    fieldPlan: 'Plan',
    fieldAddon: 'Telma on WhatsApp',
    fieldUserEmail: 'Initial user email',
    fieldUserName: 'User name',
    fieldTempPassword: 'Temporary password',
    createClinic: 'Create clinic',
    creating: 'Creating...',
    createdOk: 'Clinic created.',
    defaultSlotsNote: 'Default hours: Monday to Friday, 9am to 1pm and 2pm to 6pm.',
    consumoTitle: 'Usage',
    consumoSubtitle: 'Minutes and calls across all clinics this month.',
    totalCalls: 'Calls',
    totalMinutes: 'Minutes',
    estimatedCost: 'Estimated cost',
    perClinic: 'Per clinic',
    atividadeTitle: 'Activity',
    atividadeSubtitle: 'Recent events across all clinics.',
    atividadeEmpty: 'No recent events.',
    eventTypes: {
      call_received: 'Call answered',
      appointment_created: 'Booking created',
      appointment_confirmed: 'Booking confirmed',
      appointment_rejected: 'Booking rejected',
      limit_warning: 'Near plan limit',
      clinic_created: 'Clinic created',
    },
  },
  crm: {
    stage: {
      new: 'New',
      attempting: 'Trying to reach',
      contacted: 'Spoke to decision maker',
      interested: 'Interested',
      meeting: 'Meeting booked',
      won: 'Won',
      lost: 'Lost',
    },
    result: {
      no_answer: 'No answer',
      busy: 'Busy',
      lunch_break: 'Lunch break',
      on_holiday: 'On holiday',
      reception_no_dm: 'Reception, no decision maker',
      spoke_dm: 'Spoke to decision maker',
      interested: 'Interested',
      meeting_set: 'Meeting booked',
      won: 'Won',
      lost: 'Lost',
      other: 'Other',
    },
    activityType: {
      call: 'Call',
      whatsapp: 'WhatsApp',
      email: 'Email',
      visit: 'Visit',
      note: 'Note',
    },
    specialty: {
      dental: 'Dental',
      aesthetic: 'Aesthetics',
      veterinary: 'Veterinary',
      other: 'Other',
    },
    contactRole: { doctor: 'Doctor', reception: 'Reception', other: 'Other' },
    origin: { cold: 'Cold outreach', referral: 'Referred by' },
    country: { PT: 'Portugal', ES: 'Spain' },
    nav: {
      section: 'Sales',
      hoje: 'Today',
      prospetos: 'Clinics',
      novo: 'New',
      equipa: 'Team',
      backToPanel: 'Client panel',
    },
    today: {
      title: 'Today',
      subtitle: 'The calls you have to make, earliest first.',
      live: 'Updating live',
      overdue: 'Overdue',
      dueToday: 'Due today',
      tabToday: 'Today',
      tabNoDate: 'No date',
      scopeMine: 'Mine',
      scopeTeam: 'Whole team',
      empty: 'Nothing scheduled for today. Nice work.',
      emptyNoDate: 'Every active clinic has a next action set.',
      noDateHelp: 'Active clinics with no next action set.',
      call: 'Call',
      log: 'Log',
      lateBy: 'late',
      at: 'at',
    },
    list: {
      title: 'Pipeline clinics',
      subtitle: 'Prospects still being sold to. Not clients.',
      searchPlaceholder: 'Search by name, area or phone...',
      filters: 'Filters',
      filterRep: 'Rep',
      filterCountry: 'Country',
      filterStage: 'Stage',
      filterOrigin: 'Origin',
      referredOnly: 'Referred only',
      coldOnly: 'Cold outreach only',
      filterFrom: 'Next action from',
      filterTo: 'to',
      unassignedOnly: 'Unassigned only',
      mine: 'Mine only',
      apply: 'Apply',
      clear: 'Clear',
      empty: 'No clinics match these filters.',
      results: 'clinics',
      export: 'Export to Excel',
      take: 'Take this one',
      taken: 'Assigned to you',
      colName: 'Clinic',
      colStage: 'Stage',
      colRep: 'Rep',
      colNext: 'Next action',
      colZone: 'Area',
      noNext: 'No date',
      unassigned: 'Unassigned',
      viewList: 'List',
      viewMap: 'Map',
      openRecord: 'Open record',
      directions: 'Directions',
      nearMe: 'Near me',
      locating: 'Locating...',
      noPosition: 'Could not get your location.',
      noPins: 'None of these clinics has a mapped address.',
    },
    log: {
      title: 'What happened?',
      what: 'Result',
      note: 'Note',
      notePlaceholder: 'e.g. Ana at reception says try at 2.30pm',
      next: 'Contact again',
      tomorrowMorning: 'Tomorrow 9am',
      tomorrowAfternoon: 'Tomorrow 2pm',
      inTwoHours: 'In 2 hours',
      pickDateTime: 'Pick',
      noNext: 'No date',
      save: 'Save',
      saving: 'Saving...',
      queued: 'Saved on your phone. It will send when you have signal.',
      offline: 'Offline',
      close: 'Close',
      needResult: 'Pick a result.',
    },
    detail: {
      call: 'Call',
      whatsapp: 'WhatsApp',
      contacts: 'Contacts',
      addContact: 'Add contact',
      contactName: 'Name',
      contactRole: 'Role',
      contactPhone: 'Phone',
      contactNotes: 'Notes',
      noContacts: 'No contacts yet.',
      history: 'History',
      noHistory: 'Nothing logged yet. Make the first call.',
      logCall: 'Log a call',
      nextAction: 'Next action',
      noNextAction: 'No next action set.',
      assign: 'Rep',
      assignHelp: 'Move this clinic to another rep.',
      reassign: 'Reassign',
      details: 'Details',
      origin: 'Origin',
      website: 'Website',
      address: 'Address',
      convert: 'Convert to client',
      convertHelp:
        'Opens the client sign up form prefilled. Plan, schedule and phone number are still needed.',
      convertRequest: 'Request client sign up',
      convertRequested: 'Sign up requested',
      convertedTo: 'Already a client',
      openClient: 'Open client record',
      requestSent: 'The internal team has been notified.',
    },
    novo: {
      title: 'New clinic',
      help: 'Only the name is required. Everything else can come later.',
      pasteTitle: 'Paste text',
      pasteHelp: 'Paste the message you were sent and we will split the fields.',
      pastePlaceholder: 'e.g. Clinic X, Dr Smith, 12 Flower Street, 912 345 678',
      pasteAction: 'Split into fields',
      name: 'Clinic name',
      phone: 'Phone',
      zone: 'Area or city',
      specialty: 'Speciality',
      country: 'Country',
      address: 'Address',
      website: 'Website',
      origin: 'Origin',
      originNote: 'Referred by',
      originNotePlaceholder: 'e.g. Monica, Colgate',
      contactTitle: 'Contact (optional)',
      create: 'Create clinic',
      creating: 'Creating...',
      dupTitle: 'Does this already exist?',
      dupProspect: 'In the pipeline',
      dupClient: 'Already a client',
      dupAssigned: 'Rep:',
      dupUnassigned: 'Unassigned',
      dupOpen: 'Open',
      dupCreateAnyway: 'Create anyway',
      dupChecking: 'Checking...',
    },
    resumo: {
      title: 'Summary',
      subtitle: 'How your pipeline stands, at a glance.',
      attention: 'Needs you',
      overdue: 'Overdue actions',
      noDate: 'No date set',
      unassigned: 'Unassigned in your area',
      funnel: 'Clinic stages',
      funnelHint: 'Tap a stage to see the list.',
      byZone: 'By area',
      byZoneHint: 'Clinics still to contact, where the work is.',
      otherZones: 'other areas',
      week: 'Last 7 days',
      weekCalls: 'Logged',
      weekClinics: 'Clinics touched',
      weekInterested: 'Interested',
      weekWon: 'Won',
      empty: 'No clinics in your pipeline yet.',
      nothingPending: 'Nothing overdue and nothing in limbo. You are up to date.',
    },
    team: {
      title: 'Sales team',
      subtitle: 'Per rep summary and access management.',
      summary: 'Summary',
      newRep: 'New rep',
      newRepHelp: 'Creates the login. The rep signs in at /login with these details.',
      fullName: 'Name',
      email: 'Email',
      tempPassword: 'Temporary password',
      country: 'Country',
      territory: 'Area or territory',
      language: 'App language',
      repRole: 'Profile',
      create: 'Create rep',
      creating: 'Creating...',
      active: 'Active',
      inactive: 'Inactive',
      activate: 'Activate',
      deactivate: 'Deactivate',
      activeProspects: 'Active clinics',
      overdue: 'Overdue actions',
      wonThisMonth: 'Won this month',
      noReps: 'No reps yet.',
      unassignedPool: 'Unassigned',
    },
  },
}
