import type { Dictionary } from './types'

export const en: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'Loading...',
    errorTitle: 'Something went wrong',
    errorGeneric: 'We could not complete the action. Please try again.',
    retry: 'Try again',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Saved',
    cancel: 'Cancel',
    back: 'Back',
    search: 'Search',
    all: 'All',
    none: 'None',
    today: 'Today',
    signOut: 'Sign out',
    language: 'Language',
    copy: 'Copy',
    copied: 'Copied',
    patient: 'Patient',
    phone: 'Mobile',
    email: 'Email',
    name: 'Name',
    reason: 'Reason',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    actions: 'Actions',
    summary: 'Summary',
    of: 'of',
    thisMonth: 'this month',
    optional: 'optional',
  },
  status: {
    appointment: {
      pendente: 'To confirm',
      confirmada: 'Confirmed',
      rejeitada: 'Rejected',
      copiada: 'Copied to system',
      cancelada: 'Cancelled',
      expirada: 'Expired',
    },
    clinic: { ativa: 'Active', pausada: 'Paused', cancelada: 'Cancelled' },
    call: {
      marcacao: 'Booking',
      transferida: 'Transferred',
      informacao: 'Information',
      nao_resolvida: 'Unresolved',
    },
    origin: { telefone: 'Phone', whatsapp: 'WhatsApp' },
    channel: { telefone: 'Call', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Essencial',
    clinica: 'Clínica',
    rede: 'Rede',
    personalizado: 'Personalizado',
  },
  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  auth: {
    title: 'Sign in',
    subtitle: 'Access your clinic dashboard.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalid: 'Wrong email or password.',
    forgot: 'Forgotten your password?',
    resetTitle: 'Reset your password',
    resetLead: 'Enter the email you sign in with. We will send a link to set a new one.',
    resetSend: 'Send the link',
    resetSending: 'Sending...',
    resetSent: 'If that email has an account, a link is on its way. Check the spam folder too.',
    resetBack: 'Back to sign in',
    newTitle: 'Set a new password',
    newLead: 'Type it twice, so you do not end up with one you cannot remember.',
    newPassword: 'New password',
    newRepeat: 'Repeat it',
    newSave: 'Save and sign in',
    newSaving: 'Saving...',
    newTooShort: 'At least eight characters.',
    newMismatch: 'The two do not match.',
    newExpired: 'This link is no longer valid. Ask for another.',
  },
  panels: {
    clinica: 'Clinic',
    interno: 'Clients',
    crm: 'Sales',
    switch: 'Switch panel',
    openClinicPanel: "Open this clinic's panel",
    viewingAs: 'You are viewing the panel of',
    readOnly: 'read only, nothing is changed',
    exitView: 'Leave this view',
  },
  clinicNav: {
    hoje: 'Agenda',
    marcacoes: 'Bookings',
    horarios: 'Hours',
    chamadas: 'Conversations',
    conta: 'My clinic',
    telma: 'Telma',
    testCall: 'Simulator',
  },
  telmaSettings: {
    title: 'What Telma knows about your clinic',
    lead: 'Everything you told us at sign-up. Change it whenever you like: the next call already knows.',
  },
  agenda: {
    title: 'Agenda',
    greeting: 'Your clinic day, always up to date.',
    live: 'Live',
    liveLost: 'Connection lost — reconnecting',
    liveRetry: 'Refresh now',
    updated: 'Updated at',
    attention: 'Waiting for you',
    attentionNone: 'Nothing waiting. The agenda is up to date.',
    needsAnswer: 'To confirm',
    justCancelled: 'Cancelled',
    cancelledBy: 'Cancelled by the patient',
    slotFreed: 'Slot free',
    dayBefore: 'Yesterday',
    dayToday: 'Today',
    dayAfter: 'Tomorrow',
    pickDay: 'Pick a day',
    now: 'now',
    emptyDay: 'No bookings on this day.',
    closedDay: 'The clinic is closed on this day.',
    doneTitle: 'What Telma did today',
    doneCalls: 'Calls answered',
    doneWhatsapp: 'WhatsApp conversations',
    doneBookings: 'Bookings made',
    doneCancelled: 'Cancellations',
    doneInfo: 'Questions answered',
    seeConversations: 'See every conversation',
    openConversation: 'Read the conversation',
    seen: 'Got it',
    seenDone: 'Seen',
    holdConfirmIn: 'Confirm within',
    holdCritical: 'About to expire.',
    holdExpired: 'The slot is free again',
    holdAria: 'Time left to confirm',
  },
  conversas: {
    title: 'Conversations',
    subtitle: 'Everything Telma answered, on the phone and on WhatsApp.',
    subtitleNoWhatsapp: 'Everything Telma answered on the phone.',
    filterChannel: 'Channel',
    empty: 'No conversations for these filters.',
    transcript: 'Transcript',
    showTranscript: 'Read the conversation',
    hideTranscript: 'Close the conversation',
    noTranscript: 'This conversation has no transcript.',
    speakerTelma: 'Telma',
    speakerPatient: 'Patient',
    booked: 'Booking',
  },
  internoNav: {
    clinicas: 'Clinics',
    consumo: 'Usage',
    atividade: 'Activity',
  },
  hoje: {
    title: 'Today',
    greeting: 'Your clinic day with Telma.',
    live: 'Updating in real time',
    pendingTitle: 'To confirm',
    pendingEmpty: 'No bookings to confirm.',
    callsTitle: 'Calls today',
    callsEmpty: 'Telma has not answered any calls today yet.',
    seeAll: 'See all calls',
  },
  marcacoes: {
    title: 'Bookings',
    help: 'Telma leaves bookings here. Confirm each one and copy it into your clinic software.',
    empty: 'No bookings right now.',
    confirm: 'Confirm',
    alter: 'Change',
    reject: 'Reject',
    copyData: 'Copy patient details',
    copiedToSystem: 'Copied to clinic system',
    copiedToSystemHint: 'You can now copy this booking into your software.',
    alterWarning: 'When you change the date or time, the patient must be told.',
    newDateTime: 'New date and time',
    rejectReason: 'Reason (optional)',
    rejectReasonHint: 'Kept for the record, the patient is not told automatically.',
    confirmConfirm: 'Mark as confirmed',
    filterAll: 'All',
    filterPending: 'To confirm',
  },
  horarios: {
    title: 'Hours',
    openLabel: 'Opens',
    closeLabel: 'Closes',
    addWindow: 'Add a period',
    removeWindow: 'Remove',
    closedDay: 'Closed',
    stepLabel: 'Appointments can start every',
    stepHelp: 'How often Telma may start an appointment. Each service takes the length you gave it.',
    overlaps: 'Two periods overlap on that day.',
    addProfessional: 'There is more than one of us',
    professionalName: 'Name of whoever sees patients',
    professionalHint: 'Each person keeps their own diary and their own hours. Telma books whoever is free, or whoever is asked for.',
    everyone: 'Everyone',
    renameProfessional: 'Rename',
    removeProfessional: 'Remove',
    lastProfessional: 'At least one diary has to remain.',
    help: 'Telma only offers these hours. She will never book outside them.',
    gridHint: 'Tap the hours you want to offer on each day.',
    gridReadOnly: 'The hours this clinic has available on each day.',
    capacityNote: 'Each hour takes one booking. Talk to us to change this.',
    blockedTitle: 'Blocked days',
    blockedHelp: 'Public holidays and time off. Telma books nothing on these days.',
    addBlock: 'Block a day',
    blockDayLabel: 'Day to block',
    blockReason: 'Reason',
    noBlocked: 'No blocked days.',
    remove: 'Remove',
    saving: 'Saving...',
    planTitle: 'Planning',
    planHelp: 'Look weeks and months ahead so you can organise in good time.',
    viewWeek: 'Week',
    viewMonth: 'Month',
    prev: 'Previous',
    next: 'Next',
    thisWeek: 'This week',
    thisMonth: 'This month',
    closed: 'Closed',
    blocked: 'Blocked',
    free: 'Free',
    booking: 'booking',
    bookings: 'bookings',
    openDay: 'Open the day',
    blockThisDay: 'Block this day',
  },
  chamadas: {
    title: 'Calls',
    filterResult: 'Result',
    filterFrom: 'From',
    filterTo: 'To',
    empty: 'No calls for these filters.',
    detail: 'Call detail',
    noSummary: 'No summary.',
    audio: 'Recording',
    noAudio: 'No recording available.',
    duration: 'Duration',
  },
  conta: {
    title: 'My clinic',
    clinicData: 'Clinic details',
    plan: 'Plan',
    addon: 'Telma on WhatsApp',
    addonOn: 'Active',
    addonOff: 'Not active',
    usageTitle: 'Usage this month',
    minutesUsed: 'Minutes used',
    limit: 'Plan limit',
    contactSupport: 'To change your plan or details, talk to us.',
    brandingTitle: 'How the panel looks',
    brandingHelp: 'The logo and colour your team sees when they sign in.',
    logo: 'Logo',
    logoHelp: 'PNG, JPG, WebP or SVG, up to 1 MB. It sits in the corner of the panel.',
    logoChoose: 'Choose a file',
    logoRemove: 'Remove',
    logoSaving: 'Saving...',
    logoTooBig: 'The file is larger than 1 MB.',
    logoBadType: 'Use PNG, JPG, WebP or SVG.',
    accentTitle: 'Accent colour',
    accentHelp: 'Used on buttons and highlights. Every one has been checked to read clearly.',
    accents: {
      brand: 'Telma green',
      ocean: 'Blue',
      plum: 'Plum',
      clay: 'Terracotta',
      slate: 'Graphite',
    },
    holdTitle: 'Bookings waiting to be confirmed',
    holdHelp: 'What happens to a booking while nobody at the clinic has answered it.',
    holdAutoTitle: 'The slot is released after {minutes} minutes',
    holdAutoHelp:
      'If nobody confirms, Telma can offer that time to the next patient. Right for a clinic with somebody at the desk during the day.',
    holdManualTitle: 'It waits for an answer',
    holdManualHelp:
      'The booking holds its slot until somebody confirms or turns it down, with no deadline. Nothing disappears overnight.',
  },
  billing: {
    minutesTitle: 'Minutes available',
    percentUsed: 'used',
    minutesWord: 'minutes',
    minuteWord: 'minute',
    remaining: 'left',
    includesPurchased: 'Includes purchased minutes:',
    nearLimit: 'You are close to the plan limit. You can buy minutes at any time.',
    exhausted:
      'No minutes left this month. Telma keeps answering, but will not book new appointments until you buy minutes.',
    insteadOf: 'instead of',
    readOnly: 'A visit buys nothing. The clinic buys from its own panel.',
    buyCta: 'Buy minutes',
    buyTitle: 'Buy minutes',
    minutesPerPack: 'minutes per pack',
    minutesAdded: 'minutes added.',
    quantity: 'How many packs',
    quantityLess: 'One pack fewer',
    quantityMore: 'One pack more',
    coupon: 'Promo code (optional)',
    couponPlaceholder: 'WELCOME10',
    couponApplied: 'discount applied',
    couponUnknown: 'We do not recognise that code.',
    discount: 'Discount',
    toPay: 'To pay',
    confirm: 'Buy for',
    working: 'Processing...',
    buyHelp: 'Prices exclude VAT. The minutes are available as soon as the purchase is recorded.',
    planTitle: 'Your plan',
    planName: 'Plan',
    price: 'Price',
    priceOnRequest: 'On request',
    perMonth: '/month',
    perYear: '/year',
    includedMinutes: 'Minutes included',
    renewsAt: 'Next renewal',
    locations: 'Locations included',
    changePlanHelp: 'To change plan or add locations, talk to us.',
    addonsTitle: 'Extras',
    addonActive: 'Active',
    addonIncluded: 'Included in the plan',
    addonActivate: 'Turn on',
    addonSoon: 'Coming soon',
    addonNotOnPlan: 'Not available on this plan',
    addonFree: 'No charge',
    historyTitle: 'Purchases',
    historyEmpty: 'No purchases yet.',
    colItem: 'Item',
    colQuantity: 'Qty',
    colPrice: 'Amount',
    status: {
      pending: 'Pending',
      completed: 'Paid',
      failed: 'Failed',
      refunded: 'Refunded',
    },
    errors: {
      demo: 'Nothing is bought in the demo.',
      forbidden: 'Only the clinic buys, from its own panel.',
      item: 'That item is no longer available.',
      plan_incompatible: 'This extra is not available on your plan.',
      already_active: 'This extra is already on.',
      coming_soon: 'Not available yet. We will let you know.',
      generic: 'That did not go through. Please try again.',
    },
  },
  testCall: {
    title: 'Simulate a call',
    subtitle: 'The same run Telma makes on a real call, without a phone.',
    warning:
      'This writes to the database for real: the booking lands in the agenda and the minutes come off the plan. That is why it only exists outside production.',
    stateClinic: 'Clinic',
    statePlan: 'Plan',
    stateMinutes: 'Minutes used',
    stateAddons: 'Extras on',
    stateNoAddons: 'None',
    patientName: 'Patient name',
    duration: 'Call length',
    minutesWord: 'minutes',
    resultType: 'How the call ended',
    results: {
      marcacao: {
        label: 'Booking',
        help: 'The patient wants an appointment and Telma looks for a free time.',
      },
      transferida: {
        label: 'Transferred',
        help: 'It is urgent and the call goes to reception.',
      },
      informacao: {
        label: 'Information',
        help: 'The patient only asks a question. Nothing is booked.',
      },
    },
    submit: 'Simulate call',
    working: 'Simulating...',
    clear: 'Delete the simulated calls',
    cleared: 'deleted.',
    steps: {
      context: 'Read the clinic context',
      availability: 'Asked for free times',
      appointment: 'Left the booking',
      call: 'Recorded the call',
    },
    bookedFor: 'Booked for',
    meter: 'Minutes used',
    seeAgenda: 'See it in the agenda',
    seeAccount: 'See it in my clinic',
    outcomes: {
      booked: {
        title: 'Appointment booked',
        description: 'Telma found a time and left {name} booked, waiting to be confirmed.',
      },
      no_minutes: {
        title: 'No minutes, no booking',
        description:
          'The plan is used up, so Telma had no times to offer {name}. The call was still answered and still counts.',
      },
      no_slots: {
        title: 'No free times',
        description:
          'The agenda has nothing free over the next few days, so {name} was left without a time.',
      },
      transferred: {
        title: 'Passed to reception',
        description: '{name} needed seeing straight away and the call was transferred.',
      },
      informed: {
        title: 'Question answered',
        description: '{name} asked about hours and services. Nothing was booked.',
      },
      error: {
        title: 'It did not run',
        description: 'The simulation did not finish.',
      },
    },
    errors: {
      forbidden: 'There is no clinic open to simulate against.',
      unavailable: 'The simulator is not available here.',
      clinic: 'The clinic could not be read.',
      generic: 'That did not run. Please try again.',
    },
  },
  interno: {
    clinicsTitle: 'Clinics',
    clinicsSubtitle: 'Every clinic and its usage this month.',
    searchPlaceholder: 'Search by name...',
    colName: 'Clinic',
    colPlan: 'Plan',
    colStatus: 'Status',
    colUsage: 'Minutes / limit',
    colActivity: 'Last activity',
    overLimit: 'Over limit',
    nearLimit: 'Near limit',
    newClinic: 'New clinic',
    never: 'No activity',
    fichaData: 'Details',
    fichaTechnical: 'Technical config',
    assignedPhone: 'Assigned number',
    agentId: 'Voice agent id',
    voiceName: 'Voice',
    fichaSlots: 'Configured hours',
    fichaCalls: 'Recent calls',
    fichaAppointments: 'Recent bookings',
    openFicha: 'Open clinic',
    newTitle: 'New clinic',
    newHelp: 'Creates the clinic, its first user and the default hours.',
    fieldClinicName: 'Clinic name',
    fieldAddress: 'Address',
    fieldPhone: 'Clinic phone',
    fieldContactEmail: 'Contact email',
    fieldPlan: 'Plan',
    fieldAddon: 'Telma on WhatsApp',
    fieldUserEmail: 'Initial user email',
    fieldUserName: 'User name',
    fieldTempPassword: 'Temporary password',
    createClinic: 'Create clinic',
    creating: 'Creating...',
    createdOk: 'Clinic created.',
    defaultSlotsNote: 'Default hours: Monday to Friday, 9am to 1pm and 2pm to 6pm.',
    consumoTitle: 'Usage',
    consumoSubtitle: 'Minutes and calls across all clinics this month.',
    totalCalls: 'Calls',
    totalMinutes: 'Minutes',
    estimatedCost: 'Estimated cost',
    perClinic: 'Per clinic',
    atividadeTitle: 'Activity',
    atividadeSubtitle: 'Recent events across all clinics.',
    atividadeEmpty: 'No recent events.',
    eventTypes: {
      call_received: 'Call answered',
      appointment_created: 'Booking created',
      appointment_confirmed: 'Booking confirmed',
      appointment_rejected: 'Booking rejected',
      limit_warning: 'Near plan limit',
      clinic_created: 'Clinic created',
    },
  },
  crm: {
    stage: {
      new: 'New',
      attempting: 'Trying to reach',
      contacted: 'Spoke to decision maker',
      interested: 'Interested',
      meeting: 'Meeting booked',
      won: 'Won',
      lost: 'Lost',
    },
    result: {
      no_answer: 'No answer',
      busy: 'Busy',
      lunch_break: 'Lunch break',
      on_holiday: 'On holiday',
      reception_no_dm: 'Reception, no decision maker',
      spoke_dm: 'Spoke to decision maker',
      interested: 'Interested',
      meeting_set: 'Meeting booked',
      won: 'Won',
      lost: 'Lost',
      other: 'Other',
    },
    activityType: {
      call: 'Call',
      whatsapp: 'WhatsApp',
      email: 'Email',
      visit: 'Visit',
      note: 'Note',
    },
    specialty: {
      dental: 'Dental',
      aesthetic: 'Aesthetics',
      veterinary: 'Veterinary',
      other: 'Other',
    },
    contactRole: { doctor: 'Doctor', reception: 'Reception', other: 'Other' },
    origin: { cold: 'Cold outreach', referral: 'Referred by' },
    country: { PT: 'Portugal', ES: 'Spain' },
    nav: {
      section: 'Sales',
      hoje: 'Today',
      prospetos: 'Clinics',
      novo: 'New',
      equipa: 'Team',
    },
    today: {
      title: 'Today',
      subtitle: 'The calls you have to make, earliest first.',
      live: 'Updating live',
      overdue: 'Overdue',
      dueToday: 'Due today',
      tabToday: 'Today',
      tabNoDate: 'No date',
      scopeMine: 'Mine',
      scopeTeam: 'Whole team',
      empty: 'Nothing scheduled for today. Nice work.',
      emptyNoDate: 'Every active clinic has a next action set.',
      noDateHelp: 'Active clinics with no next action set.',
      call: 'Call',
      log: 'Log',
      lateBy: 'late',
      at: 'at',
    },
    list: {
      title: 'Pipeline clinics',
      subtitle: 'Prospects still being sold to. Not clients.',
      searchPlaceholder: 'Search by name, area or phone...',
      filters: 'Filters',
      filterRep: 'Rep',
      filterCountry: 'Country',
      filterStage: 'Stage',
      filterOrigin: 'Origin',
      referredOnly: 'Referred only',
      coldOnly: 'Cold outreach only',
      filterFrom: 'Next action from',
      filterTo: 'to',
      unassignedOnly: 'Unassigned only',
      mine: 'Mine only',
      apply: 'Apply',
      clear: 'Clear',
      empty: 'No clinics match these filters.',
      results: 'clinics',
      export: 'Export to Excel',
      take: 'Take this one',
      taken: 'Assigned to you',
      colName: 'Clinic',
      colStage: 'Stage',
      colRep: 'Rep',
      colNext: 'Next action',
      colZone: 'Area',
      noNext: 'No date',
      unassigned: 'Unassigned',
      viewList: 'List',
      viewMap: 'Map',
      openRecord: 'Open record',
      directions: 'Directions',
      nearMe: 'Near me',
      locating: 'Locating...',
      noPosition: 'Could not get your location.',
      noPins: 'None of these clinics has a mapped address.',
    },
    log: {
      title: 'What happened?',
      what: 'Result',
      note: 'Note',
      notePlaceholder: 'e.g. Ana at reception says try at 2.30pm',
      next: 'Contact again',
      tomorrowMorning: 'Tomorrow 9am',
      tomorrowAfternoon: 'Tomorrow 2pm',
      inTwoHours: 'In 2 hours',
      pickDateTime: 'Pick',
      noNext: 'No date',
      save: 'Save',
      saving: 'Saving...',
      queued: 'Saved on your phone. It will send when you have signal.',
      offline: 'Offline',
      close: 'Close',
      needResult: 'Pick a result.',
    },
    detail: {
      call: 'Call',
      whatsapp: 'WhatsApp',
      contacts: 'Contacts',
      addContact: 'Add contact',
      contactName: 'Name',
      contactRole: 'Role',
      contactPhone: 'Phone',
      contactNotes: 'Notes',
      noContacts: 'No contacts yet.',
      history: 'History',
      noHistory: 'Nothing logged yet. Make the first call.',
      logCall: 'Log a call',
      nextAction: 'Next action',
      noNextAction: 'No next action set.',
      assign: 'Rep',
      assignHelp: 'Move this clinic to another rep.',
      reassign: 'Reassign',
      details: 'Details',
      origin: 'Origin',
      website: 'Website',
      address: 'Address',
      convert: 'Convert to client',
      convertHelp:
        'Opens the client sign up form prefilled. Plan, schedule and phone number are still needed.',
      convertRequest: 'Request client sign up',
      convertRequested: 'Sign up requested',
      convertedTo: 'Already a client',
      openClient: 'Open client record',
      requestSent: 'The internal team has been notified.',
    },
    novo: {
      title: 'New clinic',
      help: 'Only the name is required. Everything else can come later.',
      pasteTitle: 'Paste text',
      pasteHelp: 'Paste the message you were sent and we will split the fields.',
      pastePlaceholder: 'e.g. Clinic X, Dr Smith, 12 Flower Street, 912 345 678',
      pasteAction: 'Split into fields',
      name: 'Clinic name',
      phone: 'Phone',
      zone: 'Area or city',
      specialty: 'Speciality',
      country: 'Country',
      address: 'Address',
      website: 'Website',
      origin: 'Origin',
      originNote: 'Referred by',
      originNotePlaceholder: 'e.g. Monica, Colgate',
      contactTitle: 'Contact (optional)',
      create: 'Create clinic',
      creating: 'Creating...',
      dupTitle: 'Does this already exist?',
      dupProspect: 'In the pipeline',
      dupClient: 'Already a client',
      dupAssigned: 'Rep:',
      dupUnassigned: 'Unassigned',
      dupOpen: 'Open',
      dupCreateAnyway: 'Create anyway',
      dupChecking: 'Checking...',
    },
    resumo: {
      title: 'Summary',
      subtitle: 'How your pipeline stands, at a glance.',
      attention: 'Needs you',
      overdue: 'Overdue actions',
      noDate: 'No date set',
      unassigned: 'Unassigned in your area',
      funnel: 'Clinic stages',
      funnelHint: 'Tap a stage to see the list.',
      byZone: 'By area',
      byZoneHint: 'Clinics still to contact, where the work is.',
      otherZones: 'other areas',
      week: 'Last 7 days',
      weekCalls: 'Logged',
      weekClinics: 'Clinics touched',
      weekInterested: 'Interested',
      weekWon: 'Won',
      empty: 'No clinics in your pipeline yet.',
      nothingPending: 'Nothing overdue and nothing in limbo. You are up to date.',
    },
    team: {
      title: 'Sales team',
      subtitle: 'Per rep summary and access management.',
      summary: 'Summary',
      newRep: 'New rep',
      newRepHelp: 'Creates the login. The rep signs in at /login with these details.',
      fullName: 'Name',
      email: 'Email',
      tempPassword: 'Temporary password',
      country: 'Country',
      territory: 'Area or territory',
      language: 'App language',
      repRole: 'Profile',
      create: 'Create rep',
      creating: 'Creating...',
      active: 'Active',
      inactive: 'Inactive',
      activate: 'Activate',
      deactivate: 'Deactivate',
      activeProspects: 'Active clinics',
      overdue: 'Overdue actions',
      wonThisMonth: 'Won this month',
      noReps: 'No reps yet.',
      unassignedPool: 'Unassigned',
    },
  },
}
