import type { Dictionary } from './types'

export const es: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'Cargando...',
    errorTitle: 'Algo ha ido mal',
    errorGeneric: 'No se ha podido completar la acción. Inténtalo de nuevo.',
    retry: 'Reintentar',
    save: 'Guardar',
    saving: 'Guardando...',
    saved: 'Guardado',
    cancel: 'Cancelar',
    back: 'Volver',
    search: 'Buscar',
    all: 'Todas',
    none: 'Ninguna',
    today: 'Hoy',
    signOut: 'Salir',
    language: 'Idioma',
    copy: 'Copiar',
    copied: 'Copiado',
    patient: 'Paciente',
    phone: 'Teléfono',
    email: 'Email',
    name: 'Nombre',
    reason: 'Motivo',
    date: 'Fecha',
    time: 'Hora',
    status: 'Estado',
    actions: 'Acciones',
    summary: 'Resumen',
    of: 'de',
    thisMonth: 'este mes',
    optional: 'opcional',
  },
  status: {
    appointment: {
      pendente: 'Por confirmar',
      confirmada: 'Confirmada',
      rejeitada: 'Rechazada',
      copiada: 'Copiada al sistema',
    },
    clinic: { ativa: 'Activa', pausada: 'Pausada', cancelada: 'Cancelada' },
    call: {
      marcacao: 'Cita',
      transferida: 'Transferida',
      informacao: 'Información',
      nao_resolvida: 'Sin resolver',
    },
    origin: { telefone: 'Teléfono', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Esencial',
    clinica: 'Clínica',
    rede: 'Red',
    personalizado: 'Personalizado',
  },
  weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  auth: {
    title: 'Entrar',
    subtitle: 'Accede al panel de tu clínica.',
    email: 'Email',
    password: 'Contraseña',
    signIn: 'Entrar',
    signingIn: 'Entrando...',
    invalid: 'Email o contraseña incorrectos.',
  },
  clinicNav: {
    hoje: 'Hoy',
    marcacoes: 'Citas',
    horarios: 'Horarios',
    chamadas: 'Llamadas',
    conta: 'Mi clínica',
  },
  internoNav: {
    clinicas: 'Clínicas',
    consumo: 'Consumo',
    atividade: 'Actividad',
  },
  hoje: {
    title: 'Hoy',
    greeting: 'El día de tu clínica con Telma.',
    live: 'Actualizando en tiempo real',
    pendingTitle: 'Por confirmar',
    pendingEmpty: 'No hay citas por confirmar.',
    callsTitle: 'Llamadas de hoy',
    callsEmpty: 'Telma aún no ha atendido llamadas hoy.',
    seeAll: 'Ver todas las llamadas',
  },
  marcacoes: {
    title: 'Citas',
    help: 'Telma deja aquí las citas. Confírmalas y pásalas al software de la clínica.',
    empty: 'No hay citas en este momento.',
    confirm: 'Confirmar',
    alter: 'Cambiar',
    reject: 'Rechazar',
    copyData: 'Copiar datos del paciente',
    copiedToSystem: 'Copiada al sistema de la clínica',
    copiedToSystemHint: 'Ya puedes pasar esta cita a tu software.',
    alterWarning: 'Al cambiar la fecha o la hora hay que avisar al paciente.',
    newDateTime: 'Nueva fecha y hora',
    rejectReason: 'Motivo (opcional)',
    rejectReasonHint: 'Queda registrado, el paciente no recibe aviso automático.',
    confirmConfirm: 'Marcar como confirmada',
    filterAll: 'Todas',
    filterPending: 'Por confirmar',
  },
  horarios: {
    title: 'Horarios',
    help: 'Telma solo ofrece estos horarios. Nunca va a citar fuera de aquí.',
    gridHint: 'Toca las horas que quieres ofrecer cada día.',
    capacityNote: 'Cada hora acepta una cita. Habla con nosotros para cambiarlo.',
    blockedTitle: 'Días bloqueados',
    blockedHelp: 'Festivos y vacaciones. Esos días Telma no cita nada.',
    addBlock: 'Bloquear día',
    blockDayLabel: 'Día a bloquear',
    blockReason: 'Motivo',
    noBlocked: 'No hay días bloqueados.',
    remove: 'Quitar',
    saving: 'Guardando...',
  },
  chamadas: {
    title: 'Llamadas',
    filterResult: 'Resultado',
    filterFrom: 'Desde',
    filterTo: 'Hasta',
    empty: 'No hay llamadas para estos filtros.',
    detail: 'Detalle de la llamada',
    noSummary: 'Sin resumen.',
    audio: 'Grabación',
    noAudio: 'Sin grabación disponible.',
    duration: 'Duración',
  },
  conta: {
    title: 'Mi clínica',
    clinicData: 'Datos de la clínica',
    plan: 'Plan',
    addon: 'Telma en WhatsApp',
    addonOn: 'Activo',
    addonOff: 'No activo',
    usageTitle: 'Consumo del mes',
    callsUsed: 'Llamadas usadas',
    limit: 'Límite del plan',
    contactSupport: 'Para cambiar el plan o los datos, habla con nosotros.',
  },
  interno: {
    clinicsTitle: 'Clínicas',
    clinicsSubtitle: 'Todas las clínicas y su consumo este mes.',
    searchPlaceholder: 'Buscar por nombre...',
    colName: 'Clínica',
    colPlan: 'Plan',
    colStatus: 'Estado',
    colUsage: 'Llamadas / límite',
    colActivity: 'Última actividad',
    overLimit: 'Por encima del límite',
    nearLimit: 'Cerca del límite',
    newClinic: 'Nueva clínica',
    never: 'Sin actividad',
    fichaData: 'Datos',
    fichaTechnical: 'Configuración técnica',
    assignedPhone: 'Número asignado',
    agentId: 'Identificador del agente',
    voiceName: 'Voz',
    fichaSlots: 'Horarios configurados',
    fichaCalls: 'Llamadas recientes',
    fichaAppointments: 'Citas recientes',
    openFicha: 'Abrir ficha',
    newTitle: 'Nueva clínica',
    newHelp: 'Crea la clínica, el primer usuario y los horarios por defecto.',
    fieldClinicName: 'Nombre de la clínica',
    fieldAddress: 'Dirección',
    fieldPhone: 'Teléfono de la clínica',
    fieldContactEmail: 'Email de contacto',
    fieldPlan: 'Plan',
    fieldAddon: 'Telma en WhatsApp',
    fieldUserEmail: 'Email del usuario inicial',
    fieldUserName: 'Nombre del usuario',
    fieldTempPassword: 'Contraseña provisional',
    createClinic: 'Crear clínica',
    creating: 'Creando...',
    createdOk: 'Clínica creada.',
    defaultSlotsNote: 'Horarios por defecto: de lunes a viernes, 9h a 13h y 14h a 18h.',
    consumoTitle: 'Consumo',
    consumoSubtitle: 'Minutos y llamadas de todas las clínicas este mes.',
    totalCalls: 'Llamadas',
    totalMinutes: 'Minutos',
    estimatedCost: 'Coste estimado',
    perClinic: 'Por clínica',
    atividadeTitle: 'Actividad',
    atividadeSubtitle: 'Eventos recientes de todas las clínicas.',
    atividadeEmpty: 'Sin eventos recientes.',
    eventTypes: {
      call_received: 'Llamada atendida',
      appointment_created: 'Cita creada',
      appointment_confirmed: 'Cita confirmada',
      appointment_rejected: 'Cita rechazada',
      limit_warning: 'Cerca del límite del plan',
      clinic_created: 'Clínica creada',
    },
  },
  crm: {
    stage: {
      new: 'Nueva',
      attempting: 'Intentando contacto',
      contacted: 'Habló con decisor',
      interested: 'Interesada',
      meeting: 'Reunión concertada',
      won: 'Cerrada',
      lost: 'Rechazada',
    },
    result: {
      no_answer: 'No contesta',
      busy: 'Comunica',
      lunch_break: 'Hora de comer',
      on_holiday: 'De vacaciones',
      reception_no_dm: 'Recepción, sin decisor',
      spoke_dm: 'Habló con decisor',
      interested: 'Interesado',
      meeting_set: 'Reunión concertada',
      won: 'Cerrado',
      lost: 'Rechazado',
      other: 'Otro',
    },
    activityType: {
      call: 'Llamada',
      whatsapp: 'WhatsApp',
      email: 'Email',
      visit: 'Visita',
      note: 'Nota',
    },
    specialty: {
      dental: 'Dental',
      aesthetic: 'Estética',
      veterinary: 'Veterinaria',
      other: 'Otra',
    },
    contactRole: { doctor: 'Médico(a)', reception: 'Recepción', other: 'Otro' },
    origin: { cold: 'Prospección fría', referral: 'Recomendado por' },
    country: { PT: 'Portugal', ES: 'España' },
    nav: {
      section: 'Comercial',
      hoje: 'Hoy',
      prospetos: 'Clínicas',
      novo: 'Nueva',
      equipa: 'Equipo',
      backToPanel: 'Panel de clientes',
    },
    today: {
      title: 'Hoy',
      subtitle: 'Las llamadas que tienes que hacer, por orden de hora.',
      live: 'Actualizando en tiempo real',
      overdue: 'Atrasada',
      dueToday: 'Para hoy',
      tabToday: 'Hoy',
      tabNoDate: 'Sin fecha',
      scopeMine: 'Las mías',
      scopeTeam: 'Todo el equipo',
      empty: 'Nada pendiente para hoy. Buen trabajo.',
      emptyNoDate: 'Todas las clínicas activas tienen próxima acción marcada.',
      noDateHelp: 'Clínicas activas sin próxima acción definida.',
      call: 'Llamar',
      log: 'Registrar',
      lateBy: 'de retraso',
      at: 'a las',
    },
    list: {
      title: 'Clínicas del embudo',
      subtitle: 'Prospectos en fase de venta. No son clientes.',
      searchPlaceholder: 'Buscar por nombre, zona o teléfono...',
      filters: 'Filtros',
      filterRep: 'Comercial',
      filterCountry: 'País',
      filterStage: 'Estado',
      filterOrigin: 'Origen',
      referredOnly: 'Solo recomendadas',
      coldOnly: 'Solo prospección fría',
      filterFrom: 'Próxima acción desde',
      filterTo: 'hasta',
      unassignedOnly: 'Solo sin asignar',
      mine: 'Solo las mías',
      apply: 'Aplicar',
      clear: 'Limpiar',
      empty: 'No hay clínicas para estos filtros.',
      results: 'clínicas',
      export: 'Exportar a Excel',
      take: 'Quedármela',
      taken: 'Asignada a ti',
      colName: 'Clínica',
      colStage: 'Estado',
      colRep: 'Comercial',
      colNext: 'Próxima acción',
      colZone: 'Zona',
      noNext: 'Sin fecha',
      unassigned: 'Sin asignar',
      viewList: 'Lista',
      viewMap: 'Mapa',
      openRecord: 'Abrir ficha',
      directions: 'Cómo llegar',
      nearMe: 'Cerca de mí',
      locating: 'Localizando...',
      noPosition: 'No se ha podido obtener tu ubicación.',
      noPins: 'Ninguna de estas clínicas tiene dirección localizada en el mapa.',
    },
    log: {
      title: '¿Qué ha pasado?',
      what: 'Resultado',
      note: 'Nota',
      notePlaceholder: 'Ej: Ana, de recepción, dice que probemos a las 14:30',
      next: 'Volver a contactar',
      tomorrowMorning: 'Mañana 9h',
      tomorrowAfternoon: 'Mañana 14h',
      inTwoHours: 'Dentro de 2h',
      pickDateTime: 'Elegir',
      noNext: 'Sin fecha',
      save: 'Guardar',
      saving: 'Guardando...',
      queued: 'Guardado en el móvil. Se envía cuando haya cobertura.',
      offline: 'Sin cobertura',
      close: 'Cerrar',
      needResult: 'Elige un resultado.',
    },
    detail: {
      call: 'Llamar',
      whatsapp: 'WhatsApp',
      contacts: 'Contactos',
      addContact: 'Añadir contacto',
      contactName: 'Nombre',
      contactRole: 'Cargo',
      contactPhone: 'Teléfono',
      contactNotes: 'Notas',
      noContacts: 'Todavía sin contactos.',
      history: 'Historial',
      noHistory: 'Aún no hay registros. Haz la primera llamada.',
      logCall: 'Registrar llamada',
      nextAction: 'Próxima acción',
      noNextAction: 'Sin próxima acción marcada.',
      assign: 'Comercial',
      assignHelp: 'Reasignar esta clínica a otro comercial.',
      reassign: 'Reasignar',
      details: 'Datos',
      origin: 'Origen',
      website: 'Web',
      address: 'Dirección',
      convert: 'Convertir en cliente',
      convertHelp:
        'Abre el formulario de alta con los datos ya rellenos. Faltan el plan, los horarios y el número.',
      convertRequest: 'Pedir alta como cliente',
      convertRequested: 'Alta pedida',
      convertedTo: 'Ya es cliente',
      openClient: 'Abrir ficha de cliente',
      requestSent: 'El equipo interno ha sido avisado.',
    },
    novo: {
      title: 'Nueva clínica',
      help: 'Solo el nombre es obligatorio. Lo demás se añade después.',
      pasteTitle: 'Pegar texto',
      pasteHelp: 'Pega el mensaje que te han pasado y repartimos los campos.',
      pastePlaceholder: 'Ej: Clínica X, Dra. Fulana, Calle de las Flores 12, 912 345 678',
      pasteAction: 'Repartir campos',
      name: 'Nombre de la clínica',
      phone: 'Teléfono',
      zone: 'Zona o ciudad',
      specialty: 'Especialidad',
      country: 'País',
      address: 'Dirección',
      website: 'Web',
      origin: 'Origen',
      originNote: 'Quién la recomendó',
      originNotePlaceholder: 'Ej: Mónica, Colgate',
      contactTitle: 'Contacto (opcional)',
      create: 'Crear clínica',
      creating: 'Creando...',
      dupTitle: '¿Esto ya existe?',
      dupProspect: 'En el embudo',
      dupClient: 'Ya es cliente',
      dupAssigned: 'Comercial:',
      dupUnassigned: 'Sin asignar',
      dupOpen: 'Abrir',
      dupCreateAnyway: 'Crear igualmente',
      dupChecking: 'Comprobando...',
    },
    resumo: {
      title: 'Resumen',
      subtitle: 'Cómo va tu embudo, de un vistazo.',
      attention: 'Te necesitan',
      overdue: 'Acciones atrasadas',
      noDate: 'Sin fecha marcada',
      unassigned: 'Sin asignar en tu zona',
      funnel: 'Estado de las clínicas',
      funnelHint: 'Toca un estado para ver la lista.',
      byZone: 'Por zona',
      byZoneHint: 'Clínicas por contactar, donde hay más trabajo.',
      otherZones: 'otras zonas',
      week: 'Últimos 7 días',
      weekCalls: 'Registros',
      weekClinics: 'Clínicas tocadas',
      weekInterested: 'Interesadas',
      weekWon: 'Cerradas',
      empty: 'Todavía no hay clínicas en tu embudo.',
      nothingPending: 'Nada atrasado y nada en el limbo. Vas al día.',
    },
    team: {
      title: 'Equipo comercial',
      subtitle: 'Resumen por comercial y gestión de accesos.',
      summary: 'Resumen',
      newRep: 'Nuevo comercial',
      newRepHelp: 'Crea el acceso. El comercial entra en /login con estos datos.',
      fullName: 'Nombre',
      email: 'Email',
      tempPassword: 'Contraseña provisional',
      country: 'País',
      territory: 'Zona o territorio',
      language: 'Idioma de la app',
      repRole: 'Perfil',
      create: 'Crear comercial',
      creating: 'Creando...',
      active: 'Activo',
      inactive: 'Inactivo',
      activate: 'Activar',
      deactivate: 'Desactivar',
      activeProspects: 'Clínicas activas',
      overdue: 'Acciones atrasadas',
      wonThisMonth: 'Cerradas este mes',
      noReps: 'Todavía no hay comerciales.',
      unassignedPool: 'Sin asignar',
    },
  },
}
