import type { Dictionary } from './types'

export const es: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'Cargando...',
    errorTitle: 'Algo ha ido mal',
    errorGeneric: 'No se ha podido completar la acción. Inténtalo de nuevo.',
    retry: 'Reintentar',
    save: 'Guardar',
    saving: 'Guardando...',
    saved: 'Guardado',
    cancel: 'Cancelar',
    back: 'Volver',
    search: 'Buscar',
    all: 'Todas',
    none: 'Ninguna',
    today: 'Hoy',
    signOut: 'Salir',
    language: 'Idioma',
    copy: 'Copiar',
    copied: 'Copiado',
    patient: 'Paciente',
    phone: 'Teléfono',
    email: 'Email',
    name: 'Nombre',
    reason: 'Motivo',
    date: 'Fecha',
    time: 'Hora',
    status: 'Estado',
    actions: 'Acciones',
    summary: 'Resumen',
    of: 'de',
    thisMonth: 'este mes',
    optional: 'opcional',
  },
  status: {
    appointment: {
      pendente: 'Por confirmar',
      confirmada: 'Confirmada',
      rejeitada: 'Rechazada',
      copiada: 'Copiada al sistema',
      cancelada: 'Cancelada',
      expirada: 'Expirada',
    },
    clinic: { ativa: 'Activa', pausada: 'Pausada', cancelada: 'Cancelada' },
    call: {
      marcacao: 'Cita',
      transferida: 'Transferida',
      informacao: 'Información',
      nao_resolvida: 'Sin resolver',
    },
    origin: { telefone: 'Teléfono', whatsapp: 'WhatsApp' },
    channel: { telefone: 'Llamada', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Esencial',
    clinica: 'Clínica',
    rede: 'Red',
    personalizado: 'Personalizado',
  },
  weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  auth: {
    title: 'Entrar',
    subtitle: 'Accede al panel de tu clínica.',
    email: 'Email',
    password: 'Contraseña',
    signIn: 'Entrar',
    signingIn: 'Entrando...',
    invalid: 'Email o contraseña incorrectos.',
    forgot: '¿Ha olvidado la contraseña?',
    resetTitle: 'Recuperar la contraseña',
    resetLead: 'Escriba el email con el que entra. Le enviamos un enlace para poner una nueva.',
    resetSend: 'Enviar el enlace',
    resetSending: 'Enviando...',
    resetSent: 'Si ese email tiene cuenta, le acaba de llegar un enlace. Revise también el correo no deseado.',
    resetBack: 'Volver a entrar',
    newTitle: 'Ponga una contraseña nueva',
    newLead: 'Escríbala dos veces, para que no quede una que no recuerde.',
    newPassword: 'Contraseña nueva',
    newRepeat: 'Repítala',
    newSave: 'Guardar y entrar',
    newSaving: 'Guardando...',
    newTooShort: 'Al menos ocho caracteres.',
    newMismatch: 'Las dos no coinciden.',
    newExpired: 'Este enlace ya no vale. Pida uno nuevo.',
  },
  panels: {
    clinica: 'Clínica',
    interno: 'Clientes',
    crm: 'Comercial',
    switch: 'Cambiar de panel',
    openClinicPanel: 'Ver el panel de esta clínica',
    viewingAs: 'Estás viendo el panel de',
    readOnly: 'solo lectura, no se cambia nada',
    exitView: 'Salir de esta vista',
  },
  clinicNav: {
    hoje: 'Agenda',
    marcacoes: 'Citas',
    horarios: 'Horarios',
    chamadas: 'Conversaciones',
    conta: 'Mi clínica',
    telma: 'Telma',
    testCall: 'Simulador',
  },
  telmaSettings: {
    title: 'Lo que Telma sabe de su clínica',
    lead: 'Todo lo que le contó en el alta. Cámbielo cuando quiera: la próxima llamada ya lo sabe.',
  },
  agenda: {
    title: 'Agenda',
    greeting: 'El día de tu clínica, siempre al día.',
    live: 'En directo',
    liveLost: 'Sin conexión — reconectando',
    liveRetry: 'Actualizar ahora',
    updated: 'Actualizado a las',
    attention: 'Te está esperando',
    attentionNone: 'Nada pendiente. La agenda está al día.',
    needsAnswer: 'Por confirmar',
    justCancelled: 'Cancelada',
    cancelledBy: 'Cancelada por el paciente',
    slotFreed: 'Hueco libre',
    dayBefore: 'Ayer',
    dayToday: 'Hoy',
    dayAfter: 'Mañana',
    pickDay: 'Elegir día',
    now: 'ahora',
    emptyDay: 'Sin citas este día.',
    closedDay: 'La clínica no abre este día.',
    doneTitle: 'Lo que hizo Telma hoy',
    doneCalls: 'Llamadas atendidas',
    doneWhatsapp: 'Conversaciones en WhatsApp',
    doneBookings: 'Citas creadas',
    doneCancelled: 'Cancelaciones',
    doneInfo: 'Información dada',
    seeConversations: 'Ver todas las conversaciones',
    openConversation: 'Leer la conversación',
    seen: 'Ya lo vi',
    seenDone: 'Visto',
    holdConfirmIn: 'Confirma en',
    holdCritical: 'Está a punto de expirar.',
    holdExpired: 'La hora volvió a quedar libre',
    holdAria: 'Tiempo para confirmar',
  },
  conversas: {
    title: 'Conversaciones',
    subtitle: 'Todo lo que atendió Telma, por teléfono y por WhatsApp.',
    subtitleNoWhatsapp: 'Todo lo que atendió Telma por teléfono.',
    filterChannel: 'Canal',
    empty: 'No hay conversaciones para estos filtros.',
    transcript: 'Transcripción',
    showTranscript: 'Leer la conversación',
    hideTranscript: 'Cerrar la conversación',
    noTranscript: 'Esta conversación no tiene transcripción.',
    speakerTelma: 'Telma',
    speakerPatient: 'Paciente',
    booked: 'Cita',
  },
  internoNav: {
    clinicas: 'Clínicas',
    consumo: 'Consumo',
    atividade: 'Actividad',
  },
  hoje: {
    title: 'Hoy',
    greeting: 'El día de tu clínica con Telma.',
    live: 'Actualizando en tiempo real',
    pendingTitle: 'Por confirmar',
    pendingEmpty: 'No hay citas por confirmar.',
    callsTitle: 'Llamadas de hoy',
    callsEmpty: 'Telma aún no ha atendido llamadas hoy.',
    seeAll: 'Ver todas las llamadas',
  },
  marcacoes: {
    title: 'Citas',
    help: 'Telma deja aquí las citas. Confírmalas y pásalas al software de la clínica.',
    empty: 'No hay citas en este momento.',
    confirm: 'Confirmar',
    alter: 'Cambiar',
    reject: 'Rechazar',
    copyData: 'Copiar datos del paciente',
    copiedToSystem: 'Copiada al sistema de la clínica',
    copiedToSystemHint: 'Ya puedes pasar esta cita a tu software.',
    alterWarning: 'Al cambiar la fecha o la hora hay que avisar al paciente.',
    newDateTime: 'Nueva fecha y hora',
    rejectReason: 'Motivo (opcional)',
    rejectReasonHint: 'Queda registrado, el paciente no recibe aviso automático.',
    confirmConfirm: 'Marcar como confirmada',
    filterAll: 'Todas',
    filterPending: 'Por confirmar',
  },
  horarios: {
    title: 'Horarios',
    help: 'Telma solo ofrece estos horarios. Nunca va a citar fuera de aquí.',
    gridHint: 'Toca las horas que quieres ofrecer cada día.',
    gridReadOnly: 'Las horas que esta clínica tiene disponibles cada día.',
    capacityNote: 'Cada hora acepta una cita. Habla con nosotros para cambiarlo.',
    blockedTitle: 'Días bloqueados',
    blockedHelp: 'Festivos y vacaciones. Esos días Telma no cita nada.',
    addBlock: 'Bloquear día',
    blockDayLabel: 'Día a bloquear',
    blockReason: 'Motivo',
    noBlocked: 'No hay días bloqueados.',
    remove: 'Quitar',
    saving: 'Guardando...',
    planTitle: 'Planificación',
    planHelp: 'Mira las semanas y los meses que vienen para organizarte con tiempo.',
    viewWeek: 'Semana',
    viewMonth: 'Mes',
    prev: 'Anterior',
    next: 'Siguiente',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mes',
    closed: 'Cerrado',
    blocked: 'Bloqueado',
    free: 'Libre',
    booking: 'cita',
    bookings: 'citas',
    openDay: 'Ver el día',
    blockThisDay: 'Bloquear este día',
  },
  chamadas: {
    title: 'Llamadas',
    filterResult: 'Resultado',
    filterFrom: 'Desde',
    filterTo: 'Hasta',
    empty: 'No hay llamadas para estos filtros.',
    detail: 'Detalle de la llamada',
    noSummary: 'Sin resumen.',
    audio: 'Grabación',
    noAudio: 'Sin grabación disponible.',
    duration: 'Duración',
  },
  conta: {
    title: 'Mi clínica',
    clinicData: 'Datos de la clínica',
    plan: 'Plan',
    addon: 'Telma en WhatsApp',
    addonOn: 'Activo',
    addonOff: 'No activo',
    usageTitle: 'Consumo del mes',
    minutesUsed: 'Minutos usados',
    limit: 'Límite del plan',
    contactSupport: 'Para cambiar el plan o los datos, habla con nosotros.',
    brandingTitle: 'La cara del panel',
    brandingHelp: 'El logo y el color que ve tu equipo al entrar.',
    logo: 'Logo',
    logoHelp: 'PNG, JPG, WebP o SVG, hasta 1 MB. Aparece en la esquina del panel.',
    logoChoose: 'Elegir archivo',
    logoRemove: 'Quitar',
    logoSaving: 'Guardando...',
    logoTooBig: 'El archivo pesa más de 1 MB.',
    logoBadType: 'Usa PNG, JPG, WebP o SVG.',
    accentTitle: 'Color de acento',
    accentHelp: 'Se usa en los botones y en los realces. Todos están comprobados para leerse bien.',
    accents: {
      brand: 'Verde Telma',
      ocean: 'Azul',
      plum: 'Ciruela',
      clay: 'Terracota',
      slate: 'Grafito',
    },
    holdTitle: 'Reservas por confirmar',
    holdHelp: 'Qué pasa con una reserva mientras nadie de la clínica le responde.',
    holdAutoTitle: 'La hora se libera a los {minutes} minutos',
    holdAutoHelp:
      'Si nadie confirma, Telma puede volver a ofrecer esa hora al siguiente paciente. Indicado si hay alguien en recepción durante el día.',
    holdManualTitle: 'Espera respuesta',
    holdManualHelp:
      'La reserva retiene la hora hasta que alguien confirme o rechace, sin plazo. Ninguna reserva desaparece por la noche.',
  },
  billing: {
    minutesTitle: 'Minutos disponibles',
    percentUsed: 'usado',
    minutesWord: 'minutos',
    minuteWord: 'minuto',
    remaining: 'sin usar',
    includesPurchased: 'Incluye minutos comprados:',
    nearLimit: 'Está llegando al límite del plan. Puede comprar minutos cuando quiera.',
    exhausted:
      'Sin minutos este mes. Telma sigue atendiendo, pero no agenda nuevas citas hasta que compre minutos.',
    insteadOf: 'en vez de',
    readOnly: 'Una visita no compra nada. La compra se hace desde el panel de la clínica.',
    buyCta: 'Comprar minutos',
    buyTitle: 'Comprar minutos',
    minutesPerPack: 'minutos por pack',
    minutesAdded: 'minutos añadidos.',
    quantity: 'Cuántos packs',
    quantityLess: 'Un pack menos',
    quantityMore: 'Un pack más',
    coupon: 'Código promocional (opcional)',
    couponPlaceholder: 'WELCOME10',
    couponApplied: 'de descuento aplicado',
    couponUnknown: 'No reconocemos ese código.',
    discount: 'Descuento',
    toPay: 'A pagar',
    confirm: 'Comprar por',
    working: 'Procesando...',
    buyHelp: 'Precios sin IVA. Los minutos quedan disponibles en cuanto se registra la compra.',
    planTitle: 'Su plan',
    planName: 'Plan',
    price: 'Precio',
    priceOnRequest: 'A consultar',
    perMonth: '/mes',
    perYear: '/año',
    includedMinutes: 'Minutos incluidos',
    renewsAt: 'Próxima renovación',
    locations: 'Sedes incluidas',
    changePlanHelp: 'Para cambiar de plan o añadir sedes, hable con nosotros.',
    addonsTitle: 'Extras',
    addonActive: 'Activo',
    addonIncluded: 'Incluido en el plan',
    addonActivate: 'Activar',
    addonSoon: 'Muy pronto',
    addonNotOnPlan: 'No disponible en este plan',
    addonFree: 'Sin coste',
    historyTitle: 'Compras',
    historyEmpty: 'Todavía no hay compras.',
    colItem: 'Producto',
    colQuantity: 'Cant.',
    colPrice: 'Importe',
    status: {
      pending: 'Pendiente',
      completed: 'Pagado',
      failed: 'Falló',
      refunded: 'Devuelto',
    },
    errors: {
      demo: 'En la demostración no se compra nada.',
      forbidden: 'Solo la clínica compra desde su panel.',
      item: 'Ese producto ya no está disponible.',
      plan_incompatible: 'Este extra no está disponible en su plan.',
      already_active: 'Este extra ya está activo.',
      coming_soon: 'Todavía no está disponible. Le avisamos cuando lo esté.',
      generic: 'No se pudo completar. Inténtelo de nuevo.',
    },
  },
  testCall: {
    title: 'Simular una llamada',
    subtitle: 'El mismo recorrido que hace Telma en una llamada real, sin teléfono.',
    warning:
      'Esto escribe de verdad en la base de datos: la cita entra en la agenda y los minutos salen del plan. Por eso solo existe fuera de producción.',
    stateClinic: 'Clínica',
    statePlan: 'Plan',
    stateMinutes: 'Minutos usados',
    stateAddons: 'Extras activos',
    stateNoAddons: 'Ninguno',
    patientName: 'Nombre del paciente',
    duration: 'Duración de la llamada',
    minutesWord: 'minutos',
    resultType: 'Cómo acabó la llamada',
    results: {
      marcacao: {
        label: 'Cita',
        help: 'El paciente quiere consulta y Telma busca una hora libre.',
      },
      transferida: {
        label: 'Transferida',
        help: 'Es urgente y la llamada pasa a recepción.',
      },
      informacao: {
        label: 'Información',
        help: 'El paciente solo pregunta. No hay cita.',
      },
    },
    submit: 'Simular llamada',
    working: 'Simulando...',
    clear: 'Borrar las llamadas simuladas',
    cleared: 'borradas.',
    steps: {
      context: 'Leyó el contexto de la clínica',
      availability: 'Pidió las horas libres',
      appointment: 'Dejó la cita pendiente',
      call: 'Registró la llamada',
    },
    bookedFor: 'Citada para',
    meter: 'Minutos usados',
    seeAgenda: 'Ver en la agenda',
    seeAccount: 'Ver en mi clínica',
    outcomes: {
      booked: {
        title: 'Cita agendada',
        description:
          'Telma encontró hora y dejó la cita de {name} a la espera de confirmación.',
      },
      no_minutes: {
        title: 'Sin minutos, sin cita',
        description:
          'El plan está agotado, así que Telma no tuvo horas que ofrecer a {name}. La llamada se atendió igual y cuenta para el consumo.',
      },
      no_slots: {
        title: 'Sin horas libres',
        description:
          'La agenda no tiene nada libre en los próximos días, así que {name} se quedó sin hora.',
      },
      transferred: {
        title: 'Pasada a recepción',
        description: '{name} necesitaba atención inmediata y la llamada se transfirió.',
      },
      informed: {
        title: 'Pregunta respondida',
        description: '{name} preguntó por horarios y servicios. No hubo cita.',
      },
      error: {
        title: 'No salió',
        description: 'La simulación no llegó al final.',
      },
    },
    errors: {
      forbidden: 'No hay ninguna clínica abierta para simular.',
      unavailable: 'El simulador no está disponible aquí.',
      clinic: 'No se pudo leer la clínica.',
      generic: 'No se pudo simular. Inténtelo de nuevo.',
    },
  },
  interno: {
    clinicsTitle: 'Clínicas',
    clinicsSubtitle: 'Todas las clínicas y su consumo este mes.',
    searchPlaceholder: 'Buscar por nombre...',
    colName: 'Clínica',
    colPlan: 'Plan',
    colStatus: 'Estado',
    colUsage: 'Minutos / límite',
    colActivity: 'Última actividad',
    overLimit: 'Por encima del límite',
    nearLimit: 'Cerca del límite',
    newClinic: 'Nueva clínica',
    never: 'Sin actividad',
    fichaData: 'Datos',
    fichaTechnical: 'Configuración técnica',
    assignedPhone: 'Número asignado',
    agentId: 'Identificador del agente',
    voiceName: 'Voz',
    fichaSlots: 'Horarios configurados',
    fichaCalls: 'Llamadas recientes',
    fichaAppointments: 'Citas recientes',
    openFicha: 'Abrir ficha',
    newTitle: 'Nueva clínica',
    newHelp: 'Crea la clínica, el primer usuario y los horarios por defecto.',
    fieldClinicName: 'Nombre de la clínica',
    fieldAddress: 'Dirección',
    fieldPhone: 'Teléfono de la clínica',
    fieldContactEmail: 'Email de contacto',
    fieldPlan: 'Plan',
    fieldAddon: 'Telma en WhatsApp',
    fieldUserEmail: 'Email del usuario inicial',
    fieldUserName: 'Nombre del usuario',
    fieldTempPassword: 'Contraseña provisional',
    createClinic: 'Crear clínica',
    creating: 'Creando...',
    createdOk: 'Clínica creada.',
    defaultSlotsNote: 'Horarios por defecto: de lunes a viernes, 9h a 13h y 14h a 18h.',
    consumoTitle: 'Consumo',
    consumoSubtitle: 'Minutos y llamadas de todas las clínicas este mes.',
    totalCalls: 'Llamadas',
    totalMinutes: 'Minutos',
    estimatedCost: 'Coste estimado',
    perClinic: 'Por clínica',
    atividadeTitle: 'Actividad',
    atividadeSubtitle: 'Eventos recientes de todas las clínicas.',
    atividadeEmpty: 'Sin eventos recientes.',
    eventTypes: {
      call_received: 'Llamada atendida',
      appointment_created: 'Cita creada',
      appointment_confirmed: 'Cita confirmada',
      appointment_rejected: 'Cita rechazada',
      limit_warning: 'Cerca del límite del plan',
      clinic_created: 'Clínica creada',
    },
  },
  crm: {
    stage: {
      new: 'Nueva',
      attempting: 'Intentando contacto',
      contacted: 'Habló con decisor',
      interested: 'Interesada',
      meeting: 'Reunión concertada',
      won: 'Cerrada',
      lost: 'Rechazada',
    },
    result: {
      no_answer: 'No contesta',
      busy: 'Comunica',
      lunch_break: 'Hora de comer',
      on_holiday: 'De vacaciones',
      reception_no_dm: 'Recepción, sin decisor',
      spoke_dm: 'Habló con decisor',
      interested: 'Interesado',
      meeting_set: 'Reunión concertada',
      won: 'Cerrado',
      lost: 'Rechazado',
      other: 'Otro',
    },
    activityType: {
      call: 'Llamada',
      whatsapp: 'WhatsApp',
      email: 'Email',
      visit: 'Visita',
      note: 'Nota',
    },
    specialty: {
      dental: 'Dental',
      aesthetic: 'Estética',
      veterinary: 'Veterinaria',
      other: 'Otra',
    },
    contactRole: { doctor: 'Médico(a)', reception: 'Recepción', other: 'Otro' },
    origin: { cold: 'Prospección fría', referral: 'Recomendado por' },
    country: { PT: 'Portugal', ES: 'España' },
    nav: {
      section: 'Comercial',
      hoje: 'Hoy',
      prospetos: 'Clínicas',
      novo: 'Nueva',
      equipa: 'Equipo',
    },
    today: {
      title: 'Hoy',
      subtitle: 'Las llamadas que tienes que hacer, por orden de hora.',
      live: 'Actualizando en tiempo real',
      overdue: 'Atrasada',
      dueToday: 'Para hoy',
      tabToday: 'Hoy',
      tabNoDate: 'Sin fecha',
      scopeMine: 'Las mías',
      scopeTeam: 'Todo el equipo',
      empty: 'Nada pendiente para hoy. Buen trabajo.',
      emptyNoDate: 'Todas las clínicas activas tienen próxima acción marcada.',
      noDateHelp: 'Clínicas activas sin próxima acción definida.',
      call: 'Llamar',
      log: 'Registrar',
      lateBy: 'de retraso',
      at: 'a las',
    },
    list: {
      title: 'Clínicas del embudo',
      subtitle: 'Prospectos en fase de venta. No son clientes.',
      searchPlaceholder: 'Buscar por nombre, zona o teléfono...',
      filters: 'Filtros',
      filterRep: 'Comercial',
      filterCountry: 'País',
      filterStage: 'Estado',
      filterOrigin: 'Origen',
      referredOnly: 'Solo recomendadas',
      coldOnly: 'Solo prospección fría',
      filterFrom: 'Próxima acción desde',
      filterTo: 'hasta',
      unassignedOnly: 'Solo sin asignar',
      mine: 'Solo las mías',
      apply: 'Aplicar',
      clear: 'Limpiar',
      empty: 'No hay clínicas para estos filtros.',
      results: 'clínicas',
      export: 'Exportar a Excel',
      take: 'Quedármela',
      taken: 'Asignada a ti',
      colName: 'Clínica',
      colStage: 'Estado',
      colRep: 'Comercial',
      colNext: 'Próxima acción',
      colZone: 'Zona',
      noNext: 'Sin fecha',
      unassigned: 'Sin asignar',
      viewList: 'Lista',
      viewMap: 'Mapa',
      openRecord: 'Abrir ficha',
      directions: 'Cómo llegar',
      nearMe: 'Cerca de mí',
      locating: 'Localizando...',
      noPosition: 'No se ha podido obtener tu ubicación.',
      noPins: 'Ninguna de estas clínicas tiene dirección localizada en el mapa.',
    },
    log: {
      title: '¿Qué ha pasado?',
      what: 'Resultado',
      note: 'Nota',
      notePlaceholder: 'Ej: Ana, de recepción, dice que probemos a las 14:30',
      next: 'Volver a contactar',
      tomorrowMorning: 'Mañana 9h',
      tomorrowAfternoon: 'Mañana 14h',
      inTwoHours: 'Dentro de 2h',
      pickDateTime: 'Elegir',
      noNext: 'Sin fecha',
      save: 'Guardar',
      saving: 'Guardando...',
      queued: 'Guardado en el móvil. Se envía cuando haya cobertura.',
      offline: 'Sin cobertura',
      close: 'Cerrar',
      needResult: 'Elige un resultado.',
    },
    detail: {
      call: 'Llamar',
      whatsapp: 'WhatsApp',
      contacts: 'Contactos',
      addContact: 'Añadir contacto',
      contactName: 'Nombre',
      contactRole: 'Cargo',
      contactPhone: 'Teléfono',
      contactNotes: 'Notas',
      noContacts: 'Todavía sin contactos.',
      history: 'Historial',
      noHistory: 'Aún no hay registros. Haz la primera llamada.',
      logCall: 'Registrar llamada',
      nextAction: 'Próxima acción',
      noNextAction: 'Sin próxima acción marcada.',
      assign: 'Comercial',
      assignHelp: 'Reasignar esta clínica a otro comercial.',
      reassign: 'Reasignar',
      details: 'Datos',
      origin: 'Origen',
      website: 'Web',
      address: 'Dirección',
      convert: 'Convertir en cliente',
      convertHelp:
        'Abre el formulario de alta con los datos ya rellenos. Faltan el plan, los horarios y el número.',
      convertRequest: 'Pedir alta como cliente',
      convertRequested: 'Alta pedida',
      convertedTo: 'Ya es cliente',
      openClient: 'Abrir ficha de cliente',
      requestSent: 'El equipo interno ha sido avisado.',
    },
    novo: {
      title: 'Nueva clínica',
      help: 'Solo el nombre es obligatorio. Lo demás se añade después.',
      pasteTitle: 'Pegar texto',
      pasteHelp: 'Pega el mensaje que te han pasado y repartimos los campos.',
      pastePlaceholder: 'Ej: Clínica X, Dra. Fulana, Calle de las Flores 12, 912 345 678',
      pasteAction: 'Repartir campos',
      name: 'Nombre de la clínica',
      phone: 'Teléfono',
      zone: 'Zona o ciudad',
      specialty: 'Especialidad',
      country: 'País',
      address: 'Dirección',
      website: 'Web',
      origin: 'Origen',
      originNote: 'Quién la recomendó',
      originNotePlaceholder: 'Ej: Mónica, Colgate',
      contactTitle: 'Contacto (opcional)',
      create: 'Crear clínica',
      creating: 'Creando...',
      dupTitle: '¿Esto ya existe?',
      dupProspect: 'En el embudo',
      dupClient: 'Ya es cliente',
      dupAssigned: 'Comercial:',
      dupUnassigned: 'Sin asignar',
      dupOpen: 'Abrir',
      dupCreateAnyway: 'Crear igualmente',
      dupChecking: 'Comprobando...',
    },
    resumo: {
      title: 'Resumen',
      subtitle: 'Cómo va tu embudo, de un vistazo.',
      attention: 'Te necesitan',
      overdue: 'Acciones atrasadas',
      noDate: 'Sin fecha marcada',
      unassigned: 'Sin asignar en tu zona',
      funnel: 'Estado de las clínicas',
      funnelHint: 'Toca un estado para ver la lista.',
      byZone: 'Por zona',
      byZoneHint: 'Clínicas por contactar, donde hay más trabajo.',
      otherZones: 'otras zonas',
      week: 'Últimos 7 días',
      weekCalls: 'Registros',
      weekClinics: 'Clínicas tocadas',
      weekInterested: 'Interesadas',
      weekWon: 'Cerradas',
      empty: 'Todavía no hay clínicas en tu embudo.',
      nothingPending: 'Nada atrasado y nada en el limbo. Vas al día.',
    },
    team: {
      title: 'Equipo comercial',
      subtitle: 'Resumen por comercial y gestión de accesos.',
      summary: 'Resumen',
      newRep: 'Nuevo comercial',
      newRepHelp: 'Crea el acceso. El comercial entra en /login con estos datos.',
      fullName: 'Nombre',
      email: 'Email',
      tempPassword: 'Contraseña provisional',
      country: 'País',
      territory: 'Zona o territorio',
      language: 'Idioma de la app',
      repRole: 'Perfil',
      create: 'Crear comercial',
      creating: 'Creando...',
      active: 'Activo',
      inactive: 'Inactivo',
      activate: 'Activar',
      deactivate: 'Desactivar',
      activeProspects: 'Clínicas activas',
      overdue: 'Acciones atrasadas',
      wonThisMonth: 'Cerradas este mes',
      noReps: 'Todavía no hay comerciales.',
      unassignedPool: 'Sin asignar',
    },
  },
}
