import type { Dictionary } from './types'

export const pt: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'A carregar...',
    errorTitle: 'Algo correu mal',
    errorGeneric: 'Não foi possível completar a ação. Tente novamente.',
    retry: 'Tentar de novo',
    save: 'Guardar',
    saving: 'A guardar...',
    saved: 'Guardado',
    cancel: 'Cancelar',
    back: 'Voltar',
    search: 'Procurar',
    all: 'Todas',
    none: 'Nenhuma',
    today: 'Hoje',
    signOut: 'Sair',
    language: 'Idioma',
    copy: 'Copiar',
    copied: 'Copiado',
    patient: 'Paciente',
    phone: 'Telemóvel',
    email: 'Email',
    name: 'Nome',
    reason: 'Motivo',
    date: 'Data',
    time: 'Hora',
    status: 'Estado',
    actions: 'Ações',
    summary: 'Resumo',
    of: 'de',
    thisMonth: 'este mês',
    optional: 'opcional',
  },
  status: {
    appointment: {
      pendente: 'Por confirmar',
      confirmada: 'Confirmada',
      rejeitada: 'Rejeitada',
      copiada: 'Copiada para o sistema',
      cancelada: 'Cancelada',
      expirada: 'Expirada',
    },
    clinic: { ativa: 'Ativa', pausada: 'Pausada', cancelada: 'Cancelada' },
    call: {
      marcacao: 'Marcação',
      transferida: 'Transferida',
      informacao: 'Informação',
      nao_resolvida: 'Sem resolução',
    },
    origin: { telefone: 'Telefone', whatsapp: 'WhatsApp' },
    channel: { telefone: 'Chamada', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Essencial',
    clinica: 'Clínica',
    rede: 'Rede',
    personalizado: 'Personalizado',
  },
  weekdays: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
  auth: {
    title: 'Entrar',
    subtitle: 'Aceda ao painel da sua clínica.',
    email: 'Email',
    password: 'Palavra-passe',
    signIn: 'Entrar',
    signingIn: 'A entrar...',
    invalid: 'Email ou palavra-passe incorretos.',
  },
  panels: {
    clinica: 'Clínica',
    interno: 'Clientes',
    crm: 'Comercial',
    switch: 'Mudar de painel',
    openClinicPanel: 'Ver o painel desta clínica',
    viewingAs: 'Está a ver o painel de',
    readOnly: 'só leitura, nada é alterado',
    exitView: 'Sair desta vista',
  },
  clinicNav: {
    hoje: 'Agenda',
    marcacoes: 'Marcações',
    horarios: 'Horários',
    chamadas: 'Conversas',
    conta: 'A minha clínica',
    testCall: 'Simulador',
  },
  agenda: {
    title: 'Agenda',
    greeting: 'O dia da sua clínica, sempre a par.',
    live: 'Ao vivo',
    liveLost: 'Sem ligação — a reconectar',
    liveRetry: 'Atualizar agora',
    updated: 'Atualizado às',
    attention: 'A precisar de si',
    attentionNone: 'Nada à sua espera. A agenda está em dia.',
    needsAnswer: 'Por confirmar',
    justCancelled: 'Cancelada',
    cancelledBy: 'Cancelada pelo paciente',
    slotFreed: 'Hora livre',
    dayBefore: 'Ontem',
    dayToday: 'Hoje',
    dayAfter: 'Amanhã',
    pickDay: 'Escolher dia',
    now: 'agora',
    emptyDay: 'Sem marcações neste dia.',
    closedDay: 'A clínica não abre neste dia.',
    doneTitle: 'O que a Telma fez hoje',
    doneCalls: 'Chamadas atendidas',
    doneWhatsapp: 'Conversas no WhatsApp',
    doneBookings: 'Marcações feitas',
    doneCancelled: 'Cancelamentos',
    doneInfo: 'Informações dadas',
    seeConversations: 'Ver todas as conversas',
    openConversation: 'Ler a conversa',
    seen: 'Já vi',
    seenDone: 'Visto',
    holdConfirmIn: 'Confirma em',
    holdCritical: 'Está quase a expirar.',
    holdExpired: 'A hora voltou a ficar livre',
    holdAria: 'Tempo para confirmar',
  },
  conversas: {
    title: 'Conversas',
    subtitle: 'Tudo o que a Telma atendeu, ao telefone e no WhatsApp.',
    subtitleNoWhatsapp: 'Tudo o que a Telma atendeu ao telefone.',
    filterChannel: 'Canal',
    empty: 'Não há conversas para estes filtros.',
    transcript: 'Transcrição',
    showTranscript: 'Ler a conversa',
    hideTranscript: 'Fechar a conversa',
    noTranscript: 'Esta conversa não tem transcrição.',
    speakerTelma: 'Telma',
    speakerPatient: 'Paciente',
    booked: 'Marcação',
  },
  internoNav: {
    clinicas: 'Clínicas',
    consumo: 'Consumo',
    atividade: 'Atividade',
  },
  hoje: {
    title: 'Hoje',
    greeting: 'O dia da sua clínica com a Telma.',
    live: 'A atualizar em tempo real',
    pendingTitle: 'Por confirmar',
    pendingEmpty: 'Não há marcações por confirmar.',
    callsTitle: 'Chamadas de hoje',
    callsEmpty: 'A Telma ainda não atendeu chamadas hoje.',
    seeAll: 'Ver todas as chamadas',
  },
  marcacoes: {
    title: 'Marcações',
    help: 'A Telma deixa aqui as marcações. Confirme e passe cada uma para o software da clínica.',
    empty: 'Não há marcações neste momento.',
    confirm: 'Confirmar',
    alter: 'Alterar',
    reject: 'Rejeitar',
    copyData: 'Copiar dados do paciente',
    copiedToSystem: 'Copiada para o sistema da clínica',
    copiedToSystemHint: 'Já pode passar esta marcação para o seu software.',
    alterWarning: 'Ao alterar a data ou a hora, é preciso avisar o paciente.',
    newDateTime: 'Nova data e hora',
    rejectReason: 'Motivo (opcional)',
    rejectReasonHint: 'Fica registado, o paciente não é avisado automaticamente.',
    confirmConfirm: 'Marcar como confirmada',
    filterAll: 'Todas',
    filterPending: 'Por confirmar',
  },
  horarios: {
    title: 'Horários',
    help: 'A Telma só oferece estes horários. Nunca vai marcar fora daqui.',
    gridHint: 'Toque nas horas que quer disponibilizar em cada dia.',
    gridReadOnly: 'As horas que esta clínica tem disponíveis em cada dia.',
    capacityNote: 'Cada hora aceita uma marcação. Fale connosco para mudar.',
    blockedTitle: 'Dias bloqueados',
    blockedHelp: 'Feriados e férias. Nestes dias a Telma não marca nada.',
    addBlock: 'Bloquear dia',
    blockDayLabel: 'Dia a bloquear',
    blockReason: 'Motivo',
    noBlocked: 'Não há dias bloqueados.',
    remove: 'Remover',
    saving: 'A guardar...',
    planTitle: 'Planeamento',
    planHelp: 'Veja as semanas e os meses à frente para se organizar com tempo.',
    viewWeek: 'Semana',
    viewMonth: 'Mês',
    prev: 'Anterior',
    next: 'Seguinte',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mês',
    closed: 'Fechado',
    blocked: 'Bloqueado',
    free: 'Livre',
    booking: 'marcação',
    bookings: 'marcações',
    openDay: 'Ver o dia',
    blockThisDay: 'Bloquear este dia',
  },
  chamadas: {
    title: 'Chamadas',
    filterResult: 'Resultado',
    filterFrom: 'De',
    filterTo: 'Até',
    empty: 'Não há chamadas para estes filtros.',
    detail: 'Detalhe da chamada',
    noSummary: 'Sem resumo.',
    audio: 'Gravação',
    noAudio: 'Sem gravação disponível.',
    duration: 'Duração',
  },
  conta: {
    title: 'A minha clínica',
    clinicData: 'Dados da clínica',
    plan: 'Plano',
    addon: 'Telma no WhatsApp',
    addonOn: 'Ativo',
    addonOff: 'Não ativo',
    usageTitle: 'Consumo do mês',
    minutesUsed: 'Minutos usados',
    limit: 'Limite do plano',
    contactSupport: 'Para mudar o plano ou os dados, fale connosco.',
    brandingTitle: 'A cara do painel',
    brandingHelp: 'O logótipo e a cor que a sua equipa vê ao entrar.',
    logo: 'Logótipo',
    logoHelp: 'PNG, JPG, WebP ou SVG, até 1 MB. Aparece no canto do painel.',
    logoChoose: 'Escolher ficheiro',
    logoRemove: 'Remover',
    logoSaving: 'A guardar...',
    logoTooBig: 'O ficheiro é maior do que 1 MB.',
    logoBadType: 'Use PNG, JPG, WebP ou SVG.',
    accentTitle: 'Cor de destaque',
    accentHelp: 'Usada nos botões e nos realces. Todas foram verificadas para se lerem bem.',
    accents: {
      brand: 'Verde Telma',
      ocean: 'Azul',
      plum: 'Ameixa',
      clay: 'Terracota',
      slate: 'Grafite',
    },
    holdTitle: 'Reservas por confirmar',
    holdHelp:
      'O que acontece a uma pré-marcação enquanto ninguém da clínica lhe responde.',
    holdAutoTitle: 'A hora liberta-se ao fim de {minutes} minutos',
    holdAutoHelp:
      'Se ninguém confirmar, a Telma pode voltar a oferecer essa hora ao paciente seguinte. Indicado para quem tem alguém na receção durante o dia.',
    holdManualTitle: 'Fica à espera de resposta',
    holdManualHelp:
      'A pré-marcação segura a hora até alguém confirmar ou rejeitar, sem prazo. Nenhuma reserva desaparece durante a noite.',
  },
  billing: {
    minutesTitle: 'Minutos disponíveis',
    percentUsed: 'usado',
    minutesWord: 'minutos',
    minuteWord: 'minuto',
    remaining: 'por usar',
    includesPurchased: 'Inclui minutos comprados:',
    nearLimit: 'Está a chegar ao limite do plano. Pode comprar minutos quando quiser.',
    exhausted:
      'Sem minutos este mês. A Telma continua a atender, mas não marca novas consultas até comprar minutos.',
    insteadOf: 'em vez de',
    readOnly: 'Uma visita não compra nada. A compra faz-se a partir do painel da clínica.',
    buyCta: 'Comprar minutos',
    buyTitle: 'Comprar minutos',
    minutesPerPack: 'minutos por pack',
    minutesAdded: 'minutos adicionados.',
    quantity: 'Quantos packs',
    quantityLess: 'Menos um pack',
    quantityMore: 'Mais um pack',
    coupon: 'Código promocional (opcional)',
    couponPlaceholder: 'WELCOME10',
    couponApplied: 'de desconto aplicado',
    couponUnknown: 'Não reconhecemos esse código.',
    discount: 'Desconto',
    toPay: 'A pagar',
    confirm: 'Comprar por',
    working: 'A processar...',
    buyHelp: 'Preços sem IVA. Os minutos ficam disponíveis assim que a compra é registada.',
    planTitle: 'O seu plano',
    planName: 'Plano',
    price: 'Preço',
    priceOnRequest: 'Sob consulta',
    perMonth: '/mês',
    perYear: '/ano',
    includedMinutes: 'Minutos incluídos',
    renewsAt: 'Próxima renovação',
    locations: 'Sedes incluídas',
    changePlanHelp: 'Para mudar de plano ou acrescentar sedes, fale connosco.',
    addonsTitle: 'Extras',
    addonActive: 'Ativo',
    addonIncluded: 'Incluído no plano',
    addonActivate: 'Ativar',
    addonSoon: 'Em breve',
    addonNotOnPlan: 'Não disponível neste plano',
    addonFree: 'Sem custo',
    historyTitle: 'Compras',
    historyEmpty: 'Ainda não há compras.',
    colItem: 'Produto',
    colQuantity: 'Qtd.',
    colPrice: 'Valor',
    status: {
      pending: 'Pendente',
      completed: 'Pago',
      failed: 'Falhou',
      refunded: 'Devolvido',
    },
    errors: {
      demo: 'Na demonstração não se compra nada.',
      forbidden: 'Só a clínica compra a partir do seu painel.',
      item: 'Esse produto já não está disponível.',
      plan_incompatible: 'Este extra não está disponível no seu plano.',
      already_active: 'Este extra já está ativo.',
      coming_soon: 'Ainda não está disponível. Avisamos quando estiver.',
      generic: 'Não foi possível concluir. Tente de novo.',
    },
  },
  testCall: {
    title: 'Simular uma chamada',
    subtitle: 'O mesmo percurso que a Telma faz numa chamada real, sem telefone.',
    warning:
      'Isto escreve mesmo na base de dados: a marcação entra na agenda e os minutos saem do plano. Por isso só existe fora de produção.',
    stateClinic: 'Clínica',
    statePlan: 'Plano',
    stateMinutes: 'Minutos usados',
    stateAddons: 'Extras ativos',
    stateNoAddons: 'Nenhum',
    patientName: 'Nome do paciente',
    duration: 'Duração da chamada',
    minutesWord: 'minutos',
    resultType: 'Como acabou a chamada',
    results: {
      marcacao: {
        label: 'Marcação',
        help: 'O paciente quer consulta e a Telma procura uma hora livre.',
      },
      transferida: {
        label: 'Transferida',
        help: 'É urgente e a chamada passa para a receção.',
      },
      informacao: {
        label: 'Informação',
        help: 'O paciente só pergunta. Não há marcação.',
      },
    },
    submit: 'Simular chamada',
    working: 'A simular...',
    clear: 'Apagar as chamadas simuladas',
    cleared: 'apagadas.',
    steps: {
      context: 'Leu o contexto da clínica',
      availability: 'Pediu as horas livres',
      appointment: 'Deixou a pré-marcação',
      call: 'Registou a chamada',
    },
    bookedFor: 'Marcada para',
    meter: 'Minutos usados',
    seeAgenda: 'Ver na agenda',
    seeAccount: 'Ver na minha clínica',
    outcomes: {
      booked: {
        title: 'Consulta marcada',
        description:
          'A Telma encontrou hora e deixou a pré-marcação de {name} à espera de confirmação.',
      },
      no_minutes: {
        title: 'Sem minutos, sem marcação',
        description:
          'O plano está esgotado, por isso a Telma não teve horas para oferecer a {name}. A chamada foi atendida na mesma e conta para o consumo.',
      },
      no_slots: {
        title: 'Sem horas livres',
        description:
          'A agenda não tem nada livre nos próximos dias, por isso {name} ficou sem hora.',
      },
      transferred: {
        title: 'Passada para a receção',
        description: '{name} precisava de atendimento imediato e a chamada foi transferida.',
      },
      informed: {
        title: 'Pergunta respondida',
        description: '{name} perguntou por horários e serviços. Não houve marcação.',
      },
      error: {
        title: 'Não correu',
        description: 'A simulação não chegou ao fim.',
      },
    },
    errors: {
      forbidden: 'Não há nenhuma clínica aberta para simular.',
      unavailable: 'O simulador não está disponível aqui.',
      clinic: 'Não foi possível ler a clínica.',
      generic: 'Não foi possível simular. Tente de novo.',
    },
  },
  interno: {
    clinicsTitle: 'Clínicas',
    clinicsSubtitle: 'Todas as clínicas e o seu consumo este mês.',
    searchPlaceholder: 'Procurar por nome...',
    colName: 'Clínica',
    colPlan: 'Plano',
    colStatus: 'Estado',
    colUsage: 'Minutos / limite',
    colActivity: 'Última atividade',
    overLimit: 'Acima do limite',
    nearLimit: 'Perto do limite',
    newClinic: 'Nova clínica',
    never: 'Sem atividade',
    fichaData: 'Dados',
    fichaTechnical: 'Configuração técnica',
    assignedPhone: 'Número atribuído',
    agentId: 'Identificador do agente',
    voiceName: 'Voz',
    fichaSlots: 'Horários configurados',
    fichaCalls: 'Chamadas recentes',
    fichaAppointments: 'Marcações recentes',
    openFicha: 'Abrir ficha',
    newTitle: 'Nova clínica',
    newHelp: 'Cria a clínica, o primeiro utilizador e os horários por defeito.',
    fieldClinicName: 'Nome da clínica',
    fieldAddress: 'Morada',
    fieldPhone: 'Telefone da clínica',
    fieldContactEmail: 'Email de contacto',
    fieldPlan: 'Plano',
    fieldAddon: 'Telma no WhatsApp',
    fieldUserEmail: 'Email do utilizador inicial',
    fieldUserName: 'Nome do utilizador',
    fieldTempPassword: 'Palavra-passe provisória',
    createClinic: 'Criar clínica',
    creating: 'A criar...',
    createdOk: 'Clínica criada.',
    defaultSlotsNote: 'Horários por defeito: segunda a sexta, 9h às 13h e 14h às 18h.',
    consumoTitle: 'Consumo',
    consumoSubtitle: 'Minutos e chamadas de todas as clínicas este mês.',
    totalCalls: 'Chamadas',
    totalMinutes: 'Minutos',
    estimatedCost: 'Custo estimado',
    perClinic: 'Por clínica',
    atividadeTitle: 'Atividade',
    atividadeSubtitle: 'Eventos recentes de todas as clínicas.',
    atividadeEmpty: 'Sem eventos recentes.',
    eventTypes: {
      call_received: 'Chamada atendida',
      appointment_created: 'Marcação criada',
      appointment_confirmed: 'Marcação confirmada',
      appointment_rejected: 'Marcação rejeitada',
      limit_warning: 'Perto do limite do plano',
      clinic_created: 'Clínica criada',
    },
  },
  crm: {
    stage: {
      new: 'Nova',
      attempting: 'A tentar contacto',
      contacted: 'Falou com decisor',
      interested: 'Interessada',
      meeting: 'Reunião marcada',
      won: 'Fechada',
      lost: 'Recusada',
    },
    result: {
      no_answer: 'Não atende',
      busy: 'Ocupado',
      lunch_break: 'Horário de almoço',
      on_holiday: 'De férias',
      reception_no_dm: 'Receção sem decisor',
      spoke_dm: 'Falou com decisor',
      interested: 'Interessado',
      meeting_set: 'Reunião marcada',
      won: 'Fechado',
      lost: 'Recusado',
      other: 'Outro',
    },
    activityType: {
      call: 'Chamada',
      whatsapp: 'WhatsApp',
      email: 'Email',
      visit: 'Visita',
      note: 'Nota',
    },
    specialty: {
      dental: 'Dentária',
      aesthetic: 'Estética',
      veterinary: 'Veterinária',
      other: 'Outra',
    },
    contactRole: { doctor: 'Médico(a)', reception: 'Receção', other: 'Outro' },
    origin: { cold: 'Prospeção fria', referral: 'Indicado por' },
    country: { PT: 'Portugal', ES: 'Espanha' },
    nav: {
      section: 'Comercial',
      hoje: 'Hoje',
      prospetos: 'Clínicas',
      novo: 'Nova',
      equipa: 'Equipa',
    },
    today: {
      title: 'Hoje',
      subtitle: 'As chamadas que tem para fazer, por ordem de hora.',
      live: 'A atualizar em tempo real',
      overdue: 'Atrasada',
      dueToday: 'Para hoje',
      tabToday: 'Hoje',
      tabNoDate: 'Sem data',
      scopeMine: 'As minhas',
      scopeTeam: 'Toda a equipa',
      empty: 'Nada agendado para hoje. Bom trabalho.',
      emptyNoDate: 'Todas as clínicas ativas têm próxima ação marcada.',
      noDateHelp: 'Clínicas ativas sem próxima ação definida.',
      call: 'Ligar',
      log: 'Registar',
      lateBy: 'atrasada',
      at: 'às',
    },
    list: {
      title: 'Clínicas do funil',
      subtitle: 'Prospetos em fase de venda. Não são clientes.',
      searchPlaceholder: 'Procurar por nome, zona ou telefone...',
      filters: 'Filtros',
      filterRep: 'Comercial',
      filterCountry: 'País',
      filterStage: 'Estado',
      filterOrigin: 'Origem',
      referredOnly: 'Só indicadas',
      coldOnly: 'Só prospeção fria',
      filterFrom: 'Próxima ação de',
      filterTo: 'até',
      unassignedOnly: 'Só sem dono',
      mine: 'Só as minhas',
      apply: 'Aplicar',
      clear: 'Limpar',
      empty: 'Não há clínicas para estes filtros.',
      results: 'clínicas',
      export: 'Exportar Excel',
      take: 'Ficar com esta',
      taken: 'Atribuída a si',
      colName: 'Clínica',
      colStage: 'Estado',
      colRep: 'Comercial',
      colNext: 'Próxima ação',
      colZone: 'Zona',
      noNext: 'Sem data',
      unassigned: 'Sem dono',
      viewList: 'Lista',
      viewMap: 'Mapa',
      openRecord: 'Abrir ficha',
      directions: 'Como chegar',
      nearMe: 'Perto de mim',
      locating: 'A localizar...',
      noPosition: 'Não foi possível obter a sua localização.',
      noPins: 'Nenhuma destas clínicas tem morada localizada no mapa.',
    },
    log: {
      title: 'O que aconteceu?',
      what: 'Resultado',
      note: 'Nota',
      notePlaceholder: 'Ex: a Ana da receção diz para tentar às 14h30',
      next: 'Voltar a contactar',
      tomorrowMorning: 'Amanhã 9h',
      tomorrowAfternoon: 'Amanhã 14h',
      inTwoHours: 'Daqui a 2h',
      pickDateTime: 'Escolher',
      noNext: 'Sem data',
      save: 'Guardar',
      saving: 'A guardar...',
      queued: 'Guardado no telemóvel. Envia quando houver rede.',
      offline: 'Sem rede',
      close: 'Fechar',
      needResult: 'Escolha um resultado.',
    },
    detail: {
      call: 'Ligar',
      whatsapp: 'WhatsApp',
      contacts: 'Contactos',
      addContact: 'Adicionar contacto',
      contactName: 'Nome',
      contactRole: 'Cargo',
      contactPhone: 'Telefone',
      contactNotes: 'Notas',
      noContacts: 'Ainda sem contactos.',
      history: 'Histórico',
      noHistory: 'Ainda não há registos. Faça a primeira chamada.',
      logCall: 'Registar chamada',
      nextAction: 'Próxima ação',
      noNextAction: 'Sem próxima ação marcada.',
      assign: 'Comercial',
      assignHelp: 'Reatribuir esta clínica a outro comercial.',
      reassign: 'Reatribuir',
      details: 'Dados',
      origin: 'Origem',
      website: 'Site',
      address: 'Morada',
      convert: 'Converter em cliente',
      convertHelp:
        'Abre o formulário de alta com os dados já preenchidos. Falta o plano, os horários e o número.',
      convertRequest: 'Pedir alta como cliente',
      convertRequested: 'Alta pedida',
      convertedTo: 'Já é cliente',
      openClient: 'Abrir ficha de cliente',
      requestSent: 'A equipa interna foi avisada.',
    },
    novo: {
      title: 'Nova clínica',
      help: 'Só o nome é obrigatório. O resto acrescenta-se depois.',
      pasteTitle: 'Colar texto',
      pasteHelp: 'Cole a mensagem que lhe passaram e nós repartimos os campos.',
      pastePlaceholder: 'Ex: Clínica X, Dra. Fulana, Rua das Flores 12, 912 345 678',
      pasteAction: 'Repartir campos',
      name: 'Nome da clínica',
      phone: 'Telefone',
      zone: 'Zona ou cidade',
      specialty: 'Especialidade',
      country: 'País',
      address: 'Morada',
      website: 'Site',
      origin: 'Origem',
      originNote: 'Quem indicou',
      originNotePlaceholder: 'Ex: Mónica, Colgate',
      contactTitle: 'Contacto (opcional)',
      create: 'Criar clínica',
      creating: 'A criar...',
      dupTitle: 'Isto já existe?',
      dupProspect: 'No funil',
      dupClient: 'Já é cliente',
      dupAssigned: 'Comercial:',
      dupUnassigned: 'Sem dono',
      dupOpen: 'Abrir',
      dupCreateAnyway: 'Criar na mesma',
      dupChecking: 'A verificar...',
    },
    resumo: {
      title: 'Resumo',
      subtitle: 'Como está o seu funil, num relance.',
      attention: 'A precisar de si',
      overdue: 'Ações atrasadas',
      noDate: 'Sem data marcada',
      unassigned: 'Sem dono na sua zona',
      funnel: 'Estado das clínicas',
      funnelHint: 'Toque num estado para ver a lista.',
      byZone: 'Por zona',
      byZoneHint: 'Clínicas por contactar, onde há mais trabalho.',
      otherZones: 'outras zonas',
      week: 'Últimos 7 dias',
      weekCalls: 'Registos',
      weekClinics: 'Clínicas tocadas',
      weekInterested: 'Interessadas',
      weekWon: 'Fechadas',
      empty: 'Ainda não há clínicas no seu funil.',
      nothingPending: 'Nada atrasado e nada no limbo. Está em dia.',
    },
    team: {
      title: 'Equipa comercial',
      subtitle: 'Resumo por comercial e gestão de acessos.',
      summary: 'Resumo',
      newRep: 'Novo comercial',
      newRepHelp: 'Cria o acesso. O comercial entra em /login com estes dados.',
      fullName: 'Nome',
      email: 'Email',
      tempPassword: 'Palavra-passe provisória',
      country: 'País',
      territory: 'Zona ou território',
      language: 'Idioma da app',
      repRole: 'Perfil',
      create: 'Criar comercial',
      creating: 'A criar...',
      active: 'Ativo',
      inactive: 'Inativo',
      activate: 'Ativar',
      deactivate: 'Desativar',
      activeProspects: 'Clínicas ativas',
      overdue: 'Ações atrasadas',
      wonThisMonth: 'Fechadas este mês',
      noReps: 'Ainda não há comerciais.',
      unassignedPool: 'Sem dono',
    },
  },
}
